---
title: "Untitled"
author: "Caitie"
date: "2022-08-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

library(tidyverse)
library(sf)
library(here)
library(raster)
library(exactextractr)
```

# Main basins
```{r}
basin<-st_read(here("projected_data/Basins/Fiji_basins12.shp")) %>% 
  st_transform(., t_crs) %>% 
  group_by(MAIN_BAS) %>% 
  summarise(total_area = sum(area_m2, na.rm = T))

```

# Population

```{r}
pop_ras_proj<-raster(here("projected_data/Population/FJI_Pop_Grid_proj.tif"))
```

```{r}
test<-extract(pop_ras_proj, basin, fun = sum, na.rm = T)
```

# Nutrients

```{r}
sep_n<-raster(here("output_data/Nutrients/Septic_N.tif"))
dir_n<-raster(here("output_data/Nutrients/Direct_N.tif"))
```

```{r}
test_sep<-extract(sep_n, basin, fun = sum, na.rm = T)

test_dir<-extract(dir_n, basin, fun = sum, na.rm = T)
```

# Buffer

```{r}
N_P_buffers_septic<-list.files(here("output_data/Nutrients/buffers"), pattern = "septic", full.names = T)

sep_buff<-read.csv(N_P_buffers_septic[[84]])
coast_sep_buff<-read.csv(N_P_buffers_septic[[9]])

N_P_buffers_direct<-list.files(here("output_data/Nutrients/buffers"), pattern = "direct", full.names = T)

dir_buff<-read.csv(N_P_buffers_direct[[79]])
coast_dir_buff<-read.csv(N_P_buffers_direct[[37]])

```

