---
title: "Untitled"
author: "Caitie"
date: "02/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(raster)
```


# Septic N 10% removal

River buffers and coastal buffers

```{r}
test<-read.csv(here("output_data/Nutrients/Fiji_septic_nutrients_at_pourpoints.csv"))
```


```{r}
septic<-read.csv(here("output_data/Nutrients/Fiji_septic_nutrients_at_pourpoints.csv")) %>% 
  dplyr::select(MAIN_BAS, N_pourpoint, P_pourpoint) %>% 
  filter(N_pourpoint != 0 & P_pourpoint !=0) %>% 
  rename(N = N_pourpoint,
         P = P_pourpoint) %>% 
  pivot_longer(., cols = c(N, P), names_to = "type", values_to = "value") %>% 
  mutate(value = value/0.9) %>% 
  group_by(type) %>% 
  summarise(total = sum(value, na.rm = T))
```


```{r}
rm_eff<-seq(0,0.1,by = 0.01)
keep<-1-rm_eff

all<-c()

for(i in 1:length(keep)){
  print(i)
  sub<-septic %>% 
    mutate(prop_keep = keep[i],
           total2 = total*prop_keep)
  
  all<-rbind(all, sub)
}
  
```
total = total amount at pourpoints without nutrient removal
total2 = total amount at pourpoints with varying levels of nutrient removal

```{r}
leach<-all %>% 
  rename(total_rm = total2) %>% 
  mutate(total_leach = total_rm * 0.1) %>% 
  dplyr::select(-total) %>% 
  pivot_wider(., names_from = "type", values_from = c("total_rm", "total_leach"))
```


```{r}
compare<-dis %>% 
  group_by(type, prop_keep) %>% 
  summarise(Total_pp = sum(value_pp, na.rm = T),
            Total_pp_leach = sum(value_pp_leach, na.rm = T))
```
```{r}

```

