---
title: "All_nutrients_pourpoints"
author: "Caitie"
date: "14/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(sf)
library(raster)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

```

# Read in data

## Connected 

```{r}
connected<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_connected_pourpoints.shp"))
st_crs(connected)<-t_crs

connected<-st_transform(connected, t_crs)

connected<-connected %>% 
  dplyr::select(Name, N_final, P_final, MAIN_BAS) %>% 
  rename(N = N_final,
         P = P_final) %>% 
  mutate(type = "Connected")
```


## Septic

```{r}
septic<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_septic_pourpoints.shp")) %>% 
  dplyr::select(N_trt_l, P_trt_l, MAIN_BA) %>% 
  rename(N = N_trt_l,
         P = P_trt_l,
         MAIN_BAS = MAIN_BA) %>% 
  mutate(type = "Septic",
         Name = NA) %>% 
  st_transform(., t_crs)
st_crs(septic)<-t_crs
```


## Direct

```{r}
direct<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_direct_pourpoints.shp")) %>% 
  dplyr::select(N_trt_l, P_trt_l, MAIN_BA) %>% 
  rename(N = N_trt_l,
         P = P_trt_l,
         MAIN_BAS = MAIN_BA) %>% 
  mutate(type = "Direct",
         Name = NA) %>% 
  st_transform(., t_crs)

st_crs(direct)<-t_crs
```

## Coastal

```{r}
coastal_septic<-st_read(here("output_data/Nutrients_at_pourpoints/Coastal_septic_pourpoints.shp")) %>% 
  dplyr::select(spt_N__, spt_P__, MAIN_BA) %>% 
  rename(N = spt_N__,
         P = spt_P__,
         MAIN_BAS = MAIN_BA) %>% 
  mutate(type = "Coastal_septic", 
         Name = NA) %>% 
  st_transform(., t_crs) 

st_crs(coastal_septic)<-t_crs
```

```{r}
coastal_direct<-st_read(here("output_data/Nutrients_at_pourpoints/Coastal_direct_pourpoints.shp")) %>% 
  dplyr::select(drc_N__, drc_P__, MAIN_BA) %>% 
  rename(N = drc_N__,
         P = drc_P__,
         MAIN_BAS = MAIN_BA) %>% 
  mutate(type = "Coastal_direct",
         Name = NA) %>% 
  st_transform(., t_crs) 

st_crs(coastal_direct)<-t_crs
```

# Combine


```{r}
all<-rbind(connected, septic, direct, coastal_septic, coastal_direct)

all<-st_transform(all, t_crs)
```

# Write data - send data to Daniel for ocean transport model

```{r}
st_write(all, here("output_data/Nutrients_at_pourpoints/All_nutrients_at_pourpoints.shp"), delete_layer = T)
```

For some reason the CRS doesn't save...
```{r}
test<-st_read(here("output_data/Nutrients_at_pourpoints/All_nutrients_at_pourpoints.shp"))
```



