---
title: "Untitled"
author: "Caitie"
date: '2022-07-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(raster)
library(here)
library(tabularaster)
#devtools::install_github("isciences/exactextractr")
library(exactextractr)
library(tmap)
library(fasterize)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```


# Load data

## Coral reefs


```{r}
reefs<-st_read(here("projected_data/Allen_Coral_Atlas/coral_algae_fiji_crop.shp"))


#reefs_diss<-reefs %>% 
#  mutate(diss = 1) %>% 
#  group_by(class) %>% 
#  summarise(diss = sum(diss))

#st_write(reefs_diss, here("projected_data/Allen_Coral_Atlas/coral_algae_fiji_dissolve.shp"))

#reefs_diss<-st_read(here("projected_data/Allen_Coral_Atlas/coral_algae_fiji_dissolve.shp"))
```


## Plumes

These currently don't have the wave/current information added, just decay function

```{r}
r<-raster(here("output_data/Plumes/All_plumes_fiji.tif"))

reef_proj<-reefs %>% 
  st_transform(., st_crs(r))
```

```{r}
reef_ras<-fasterize(reef_proj, r)

reef_ras[is.na(reef_ras) == T]<-0

r<-resample(r, reef_ras, method = "bilinear")

reef_n<-reef_ras*r

writeRaster(reef_n, here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs.tif"), overwrite = T)
```

# Intersect coral reefs with plumes and calculates the amount of nutrients

```{r}
n_reefs<-exactextractr::exact_extract(r, reef_proj, fun = "sum")

n_df<-as.data.frame(n_reefs)

done<-cbind(reefs, n_df)

st_write(done, here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs.shp"), delete_layer = TRUE)
```

# Connected vs unconnected on reefs

```{r}
conn<-raster(here("output_data/Plumes/Connected_plume.tif"))
conn<-resample(conn, r, method = "bilinear")

unconn<-raster(here("output_data/Plumes/Unconnected_plume.tif"))
unconn<-resample(unconn, r, method = "bilinear")

```

Check - conn+unconn should equal r
```{r}
cellStats(conn, "sum")
cellStats(unconn, "sum")
cellStats(r, "sum")
```

```{r}
conn_reef_n<-reef_ras*conn
unconn_reef_n<-reef_ras*unconn

writeRaster(conn_reef_n, here("output_data/Nutrients_at_reefs/Connected_nitrogen_on_reefs.tif"), overwrite = T)
writeRaster(unconn_reef_n, here("output_data/Nutrients_at_reefs/Unconnected_nitrogen_on_reefs.tif"), overwrite = T)
```

```{r}
conn_n_reefs<-exactextractr::exact_extract(conn, reef_proj, fun = "sum")
unconn_n_reefs<-exactextractr::exact_extract(unconn, reef_proj, fun = "sum")

conn_n_df<-as.data.frame(conn_n_reefs)
unconn_n_df<-as.data.frame(unconn_n_reefs)

conn_done<-cbind(reef_proj, n_df, conn_n_df) %>% 
  cbind(unconn_n_df)

st_write(conn_done, here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs_by_treatment.shp"), delete_layer = TRUE)
```

# Nutrients on reefs by basin

```{r}
ras_files<-list.files(here("output_data/Plumes"), pattern = "5", full.names = T) %>% 
  str_subset(.,pattern="xml", negate = TRUE)

all_re<-lapply(ras_files, raster)

n_basins<-data.frame(matrix(NA, nrow = nrow(reef_proj), ncol = length(all_re)))

# Check 5120081650

for(i in 1:length(all_re)){
  print(i)
  plume<-all_re[[i]]
  plume<-resample(plume,r, method = "bilinear")
  name<-names(plume)
  name2<-str_extract(name, "[0-9]+")
  
  bas_n_reefs<-exactextractr::exact_extract(plume, reef_proj, fun = "sum")
  bas_n_reefs<-plume*reef_ras
  
  bas_n_df<-as.data.frame(bas_n_reefs)
  
  n_basins[,i]<-bas_n_df
  
  colnames(n_basins)[i]<-name2

}

basin_join<-cbind(reef_proj, n_basins)

st_write(basin_join, here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs_by_basin.shp"), delete_layer = TRUE)
```


```{r}
tmap_mode("view")
tm_shape(done) +
    tm_polygons("n_reefs")
```


