---
title: "Untitled"
author: "Caitie"
date: "16/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
#library(startR)
library(here)
library(raster)
library(gdalUtils)
library(tabularaster)
library(units)
library(rgdal)
library(lwgeom)

#source(here("scripts/plume_functions.R"))

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

# Population raster

```{r}
pop_ras_proj<-raster(here("projected_data/Population/population_fji_albers.tif"))
```

# Calculate N and P from human population

N emission (kg/person/year) are estimated based on dietary per capita protein consumption from FAO

http://www.fao.org/faostat/en/#data/FBS

```{r}
Protein_intake<- 71.14 #FAO total protein supply g/capita/day 
plant_protein_intake<-42.72 # FAO 2013 Protein Supply Vegetable products g/capita/day - this is to account for vegetal protein twice in phosphorus estimates

#Above values from year 2018
```

The human N emissions (kg/person/year) are thus

```{r}
N_excretion_human<- Protein_intake*0.13

#g/person/day assuming 13% nitrogen content of protein- This estimate is slightly lower than using the GDP_ppp estimate. Value from Wang et al. 2019 and Jönsson H., Richert Stintzing A., Vinnerås B. & Salomon E. Guidelines on use of urine and faeces in crop production (Stockholm Environment Institute, SE-103 14 Stockholm, Sweden, 2004).

#****Check about using 80% N lost in urine and 17% in faeces???#

N_emissions_human<- 0.365*N_excretion_human #kg/person/year
```

```{r}
P_excretion_human<- 0.011 * (Protein_intake + plant_protein_intake) 

# units are total protein in urine and feces g/person/day - Equation from Mihelic et al. 2011 https://reader.elsevier.com/reader/sd/pii/S0045653511001925?token=37B898436A78191398F270991D46AED05EF0C364F3BF68D80B1FFC4C1C334575343378A0F7DAD55F258716F0EDDB1D42

P_emissions_human<-0.365*P_excretion_human #kg/person/year
```

# N and P emissions per grid cell

## Connected

```{r}
conn_pop<-raster(here("output_data/Population/Connected_population.tif"))
```

```{r}
N_cell_conn<-conn_pop * N_emissions_human #kg/year/cell
P_cell_conn<-conn_pop * P_emissions_human #kg/year/cell
```

```{r}
writeRaster(N_cell_conn,here("output_data/Nutrients/Connected_N.tif"),overwrite = T)
writeRaster(P_cell_conn,here("output_data/Nutrients/Connected_P.tif"),overwrite = T)
```

## Septic

```{r}
septic_pop<-raster(here("output_data/Population/Septic_population.tif"))
```

```{r}
N_cell_septic<-septic_pop * N_emissions_human #kg/year/cell
P_cell_septic<-septic_pop * P_emissions_human #kg/year/cell
```

```{r}
writeRaster(N_cell_septic,here("output_data/Nutrients/Septic_N.tif"),overwrite = T)
writeRaster(P_cell_septic,here("output_data/Nutrients/Septic_P.tif"),overwrite = T)
```

## Direct

```{r}
direct_pop<-raster(here("output_data/Population/Direct_population.tif"))
```


```{r}
N_cell_direct<-direct_pop * N_emissions_human #kg/year/cell
P_cell_direct<-direct_pop * P_emissions_human #kg/year/cell
```

```{r}
writeRaster(N_cell_direct,here("output_data/Nutrients/Direct_N.tif"),overwrite = T)
writeRaster(P_cell_direct,here("output_data/Nutrients/Direct_P.tif"),overwrite = T)
```


