---
title: "Untitled"
author: "Caitie"
date: "18/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(here)
library(raster)
library(ggplot2)
library(rgdal)
library(gdistance)
library(reshape2)
library(rgrass7)
library(parallel)
library(tmap)
#remotes::install_github("SEEG-Oxford/seegSDM")
library(seegSDM)
library(tabularaster)
library(units)
library(lwgeom)

```
# Find the outfall pourpoints associated with rivers

```{r}
#Intersect basins with tikina
fiji_basins12<-st_read(here("projected_data/Basins/Fiji_basins12.shp")) %>% 
  mutate(bas_area_m2 = st_area(.),
         bas_area_km2 = drop_units(bas_area_m2)/1000000,
         ID = seq.int(nrow(.)))

stp_crs<-st_crs(fiji_basins12)

fiji_tik<-st_read("/home/kuempel/Waste_water_data/Fiji/Tikina/fji_polbnda_adm3_tikina.shp") %>% 
  rename(TIKINA = ADM3_NAME,
         PROVINCE = ADM2_NAME,
         TID = FBOS_TID,
         PID = FBOS_PID)

fiji_tik_merc<-st_transform(fiji_tik, stp_crs) %>% 
  st_make_valid()

fiji_basins_tik<-st_intersection(fiji_tik_merc, fiji_basins12) %>% 
  mutate(bas_tik_area_m2 = st_area(.),
         bas_tik_area_km2 = drop_units(bas_tik_area_m2)/1000000,
         ID = seq.int(nrow(.)))

fiji_rivers<-st_read(here("raw_data/Rivers/Fiji_RiverATLAS.shp"))

fiji_rivers<-st_transform(fiji_rivers, stp_crs)

fiji_tik_rivers<-st_intersection(fiji_tik_merc, fiji_rivers)

fiji_pourpoints<-st_read(here("raw_data/Rivers/Fiji_RiverATLAS_river_ends.shp"))
                         
fiji_pourpoints<-st_transform(fiji_pourpoints, stp_crs)

#fiji_tik_pp<-st_intersection(fiji_pourpoints, fiji_tik_merc)

rivers<-st_read(here("raw_data/Rivers/RiverATLAS_v10_shp/RiverATLAS_v10_au.shp"))
rivers<-st_transform(rivers, stp_crs)

#test<-rivers_merc %>% 
 # filter(HYRIV_ID == 50474738)
```


```{r}
test<-readOGR("/home/kuempel/Waste_water_data/Fiji/Sewage_plants/Fiji Wastewater Treatment plants.kml") %>% 
  st_as_sf()

test<-st_transform(test, stp_crs)

test2<-st_intersection(test, fiji_tik_merc)
```


```{r}

# Nadi River - potentially HYRIV_ID 50492092

nadi_basin<-fiji_basins_tik %>% 
  filter(TIKINA == "Nadi")

nadi_rivers<-fiji_rivers[fiji_rivers$HYBAS_L12 %in% nadi_basin$HYBAS_ID,] 

nadi_pp<-fiji_pourpoints[fiji_pourpoints$HYBAS_L12 %in% nadi_basin$HYBAS_ID,] # There are 18 pourpoints in Nadi

nadi_outfall<-nadi_pp %>% 
  filter(HYRIV_ID == 50492092) # All "connected" nutrients should be discharged from here, the rest allocated across the rivers?
  

nadi_pourpoint<-st_endpoint(nadi_outfall) %>% 
  st_sf() %>% 
  mutate(Name = "Nadi outfall",
         Tikina = "Nadi") %>% 
  dplyr::select(Name, Tikina, geometry)

```

```{r}
# Ba River 50487189?

test<-fiji_tik_rivers %>% 
  filter(TIKINA == "Ba")


ba_basin<-fiji_basins_tik %>% 
  filter(TIKINA == "Ba")

ba_rivers<-fiji_rivers[fiji_rivers$HYBAS_L12 %in% ba_basin$HYBAS_ID,] # 

table(ba_rivers$MAIN_RIV) #50487189 is the main river in Ba


ba_pp<-fiji_pourpoints[fiji_pourpoints$HYBAS_L12 %in% ba_basin$HYBAS_ID,] # There are 12 pourpoints in Ba

ba_outfall<-ba_rivers %>% 
  filter(HYRIV_ID == 50487054)  # This gets lost in the fiji rivers so we take it from the larger river shapefile, still might be a bit off????
  

ba_pourpoint<-st_endpoint(ba_outfall) %>% 
  st_sf() %>% 
  mutate(Name = "Ba outfall",
         Tikina = "Ba") %>% 
  dplyr::select(Name, Tikina, geometry)
```


```{r}
# Rewa River
rewa_basin<-fiji_basins_tik %>% 
  filter(TIKINA == "Rewa")

rewa_rivers<-fiji_rivers[fiji_rivers$HYBAS_L12 %in% rewa_basin$HYBAS_ID,] # 

table(rewa_rivers$MAIN_RIV) #50497293 is the main river in Rewa

rewa_pp<-fiji_pourpoints[fiji_pourpoints$HYBAS_L12 %in% rewa_basin$HYBAS_ID,] # There are 25 pourpoints in Rewa

rewa_outfall<-rewa_pp %>% 
  filter(HYRIV_ID == 50497293) 

rewa_pourpoint<-st_endpoint(rewa_outfall) %>% 
  st_sf() %>% 
  mutate(Name = "Rewa Outfall", 
         Tikina = "Naitasiri") %>% 
  dplyr::select(Name, Tikina, geometry)
```


```{r}
# Lebasa River
labasa_basin<-fiji_basins_tik %>% 
  filter(TIKINA == "Labasa")

labasa_rivers<-fiji_rivers[fiji_rivers$HYBAS_L12 %in% labasa_basin$HYBAS_ID,] # 

table(labasa_rivers$MAIN_RIV) #50474738 is the main river in Labasa but there are several that have a lot so check

labasa_pp<-fiji_pourpoints[fiji_pourpoints$HYBAS_L12 %in% labasa_basin$HYBAS_ID,] # There are 22 pourpoints in Rewa

labasa_outfall<-fiji_rivers %>% 
  filter(HYRIV_ID == 50473038)  # need to think more about how to do this.

#plot(st_geometry(labasa_rivers))
#plot(st_geometry(labasa_outfall), add = T, col = "red")

labasa_pourpoint<-st_endpoint(labasa_outfall) %>% 
  st_sf() %>%
  mutate(Name = "Labasa Outfall", 
         Tikina = "Labasa") %>% 
  dplyr::select(Name, Tikina, geometry)

```


```{r}
# Sigatoka River
sigatoka_basin<-fiji_basins_tik %>% 
  filter(TIKINA == "Nasigatoka")

sigatoka_rivers<-fiji_rivers[fiji_rivers$HYBAS_L12 %in% sigatoka_basin$HYBAS_ID,] # 

table(sigatoka_rivers$MAIN_RIV) #50497707 is the main river in Nasigatoka

sigatoka_pp<-fiji_pourpoints[fiji_pourpoints$HYBAS_L12 %in% sigatoka_basin$HYBAS_ID,] # There are 21 pourpoints in Rewa

sigatoka_outfall<-sigatoka_pp %>% 
  filter(HYRIV_ID == 50497707) 

sigatoka_pourpoint<-st_endpoint(sigatoka_outfall) %>% 
  st_sf() %>% 
  mutate(Name = "Sigatoka Outfall",
         Tikina = "Nasigatoka") %>% 
  dplyr::select(Name, Tikina, geometry)
```


```{r}
# ACS 

acs_basin<-fiji_basins_tik %>% 
  filter(TIKINA == "Naitasiri")

acs_rivers<-fiji_rivers[fiji_rivers$HYBAS_L12 %in% acs_basin$HYBAS_ID,] # 

table(acs_rivers$MAIN_RIV) #50497293 is the main river in Naitasiri

acs_pp<-fiji_pourpoints[fiji_pourpoints$HYBAS_L12 %in% acs_basin$HYBAS_ID,] # There are 21 pourpoints in Rewa

acs_outfall<-acs_pp %>% 
  filter(HYRIV_ID == 50497293) 

acs_pourpoint<-st_endpoint(acs_outfall) %>% 
  st_sf() %>% 
  mutate(Name = "ACS Outfall",
         Tikina = "Naitasiri") %>% 
  dplyr::select(Name, Tikina, geometry)
```

```{r}
# Naboro Prison

naboro_basin<-fiji_basins_tik %>% 
  filter(TIKINA == "Suva")

naboro_rivers<-fiji_rivers[fiji_rivers$HYBAS_L12 %in% sigatoka_basin$HYBAS_ID,] # 

table(naboro_rivers$MAIN_RIV) #50497707 is the main river in Suva

naboro_pp<-fiji_pourpoints[fiji_pourpoints$HYBAS_L12 %in% naboro_basin$HYBAS_ID,] # There are 21 pourpoints in Rewa

naboro_outfall<-fiji_rivers %>% 
  filter(HYRIV_ID == 50497707) 

naboro_pourpoint<-st_endpoint(naboro_outfall) %>% 
  st_sf() %>% 
  mutate(Name = "Naboro Outfall",
         Tikina = "Suva") %>% 
  dplyr::select(Name, Tikina, geometry)
```

```{r}
# Wailada
wailada_basin<-fiji_basins_tik %>% 
  filter(TIKINA == "Suva")

wailada_rivers<-fiji_rivers[fiji_rivers$HYBAS_L12 %in% sigatoka_basin$HYBAS_ID,] # 

table(wailada_rivers$MAIN_RIV) #50497707 is the main river in Suva

wailada_pp<-fiji_pourpoints[fiji_pourpoints$HYBAS_L12 %in% naboro_basin$HYBAS_ID,] # There are 21 pourpoints in Rewa

wailada_outfall<-fiji_rivers %>% 
  filter(HYRIV_ID == 50497707) 

wailada_pourpoint<-st_endpoint(wailada_outfall) %>% 
  st_sf() %>% 
  mutate(Name = "Wailada Outfall",
         Tikina = "Suva") %>% 
  dplyr::select(Name, Tikina, geometry)

```

# Location of other outfalls (located from google earth)

```{r}
stp<-readOGR("/home/kuempel/Waste_water_data/Fiji/Sewage_plants/Fiji Wastewater Treatment plants.kml") %>% 
  st_as_sf()

stp_outfalls<-stp %>% 
  filter(stringr::str_detect(Name, 'Outfall') )

stp_outfalls_merc<-st_transform(stp_outfalls, crs = st_crs(stp_crs)) %>% 
  st_zm() %>% 
  dplyr::select(Name, geometry) %>% 
  mutate(Tikina = ifelse(Name == "Pacific Harbor Sewage Outfall", "Serua",
                         ifelse(Name == "Lautoka Natabua Sewage Outfall", "Vuda", "Suva")))
```

# Combine all STP pourpoints

```{r}

stp_all<- rbind(stp_outfalls_merc, nadi_pourpoint,  rewa_pourpoint, sigatoka_pourpoint, labasa_pourpoint, ba_pourpoint, acs_pourpoint, naboro_pourpoint, wailada_pourpoint)

stp_all_df<-stp_all %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry)

st_write(stp_all,here("output_data/Sewage_plants/All_STP_outfalls_Fiji.shp"), delete_layer = T)
```
