---
title: "Untitled"
author: "Caitie"
date: "14/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(here)
library(raster)
library(ggplot2)
library(rgdal)
library(gdistance)
library(reshape2)
library(rgrass7)
library(parallel)
library(tmap)
#remotes::install_github("SEEG-Oxford/seegSDM")
library(seegSDM)
library(tabularaster)
library(units)
library(lwgeom)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

# Nutrients at each pourpoint

```{r}
stp_crs<-st_read(here("output_data/Sewage_plants/Nutrients_at_STP.shp")) %>% 
  st_transform(., crs = t_crs)

stp<-stp_crs %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry)
```

# Location of pourpoints

```{r}
basins12<-st_read(here("projected_data/Basins/Fiji_basins12.shp")) %>% 
  st_transform(., t_crs) %>% 
  group_by(MAIN_BAS) %>% 
  summarise(total_area = sum(area_m2, na.rm = T))
```



```{r}
# Ba is 50487189 but this doesn't appear in river shapefile so we take the other
# Removed Ba 50487189,  and Labasa 50474738 and looked up outfalls manually
pp_mainriv<-c(50489575, 50492092, 50497050, 50497707, 50497293, 50498761)
stp_names<-c("Lautoka", "Nadi", "Kinoya", "Sigatoka", "Rewa", "Deuba")
pp_df<-data.frame(STP = stp_names, mainriv = pp_mainriv)

rivers<-st_read(here("projected_data/Rivers/Fiji_rivers.shp"))
rivers_proj<-st_transform(rivers, crs = t_crs)

sub_fiji_rivers<- rivers_proj %>% 
  filter(NEXT_DOWN == 0) %>% 
  st_cast(., "LINESTRING") %>% 
  filter(MAIN_RIV %in% pp_df$mainriv) %>% 
  filter(!duplicated(HYRIV_ID)) %>% 
  left_join(., pp_df, by = c("MAIN_RIV" = "mainriv")) %>% 
  dplyr::select(HYRIV_ID, NEXT_DOWN, MAIN_RIV, STP) 
```

```{r}
pnts<-st_endpoint(sub_fiji_rivers) 
pnts_xy<-st_coordinates(pnts) 

data_per_river<-cbind(sub_fiji_rivers, pnts_xy) %>% 
  rename(pp_x = X,
         pp_y = Y) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry)

```


```{r}
stp_pp<-st_read(here("output_data/Sewage_plants/All_STP_outfalls_Fiji.shp")) %>% 
  st_transform(., crs = t_crs) %>% 
    mutate(ID = ifelse(Name == "Pacific Harbor Sewage Outfall", 1,
                            ifelse(Name == "PWD (Kinoya) Sewage Outfall" , 2,
                                   ifelse(Name == "Naboro", NA,
                                          ifelse(Name == "Nadali", 3,
                                                 ifelse(Name ==  "Labasa Outfall", 4,
                                                        ifelse(Name == "Lautoka Natabua Sewage Outfall", 5,
                                                               ifelse(Name ==  "Nadi Outfall" , 6,
                                                                      ifelse(Name == "Sigatoka Outfall", 7,
                                                                             ifelse(Name == "Ba River Outfall", 8, NA))))))))))

stp_pp_proj<-st_transform(stp_pp, crs = t_crs) %>% 
  mutate(ID = ifelse(Name == "Rewa Outfall", 3, 
                     ifelse(Name == "ACS Outfall",NA,
                            ifelse(Name == "Naboro Outfall", NA,
                                   ifelse(Name == "Wailada Outfall", NA, as.numeric(ID)))))) %>% 
  filter(!is.na(ID) == T)

```

```{r}
pp_nutri<-data_per_river %>% 
  dplyr::select(HYRIV_ID, MAIN_RIV, STP, pp_x, pp_y) %>% 
  mutate(ID = case_when(STP == "Labasa" ~ 4,
                        STP == "Ba"~ 8,
                        STP == "Lautoka" ~ 5,
                        STP == "Nadi" ~ 6,
                        STP == "Kinoya" ~ 2,
                        STP == "Rewa" ~ 3,
                        STP == "Sigatoka" ~ 7,
                        STP == "Deuba" ~ 1)) %>% 
  left_join(., stp, by = "ID")

```

```{r}
pour_points<-pp_nutri
pour_points<-left_join(stp_pp_proj, stp, by = "ID") %>% 
  st_transform(., crs= t_crs) 

st_crs(pour_points)<-t_crs

pour_points<-st_transform(pour_points, crs = t_crs)

pour_points_final<-st_intersection(pour_points, basins12)

test<-pour_points %>% 
  filter(!STP_x %in% pour_points_final$STP_x)

test2<-basins12[st_nearest_feature(test, basins12),] %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry)

test3<-cbind(test, test2)

pour_points_final2<-rbind(pour_points_final, test3)

st_write(pour_points_final2, here("output_data/Nutrients_at_pourpoints/Fiji_connected_pourpoints.shp"), delete_layer = T)

```



