---
title: "Untitled"
author: "Caitie"
date: "12/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(gdalUtils)
library(here)
library(raster)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

# ACA Fiji 


```{r}
reef<-st_read("/home/kuempel/Fiji_sewage/raw_data/Allen_Coral_Atlas/benthic.shp")

reef_proj<-reef %>% 
  st_transform(., t_crs)

gdalwarp(srcfile = "/home/kuempel/Fiji_sewage/raw_data/Allen_Coral_Atlas/benthic.shp",
         dstfile = "/home/kuempel/Fiji_sewage/projected_data/Allen_Coral_Atlas/benthic_proj.shp",
         t_srs = t_crs)

sub_reef<-reef %>% 
  filter(class == "Coral/Algae")

st_write(sub_reef, "/home/kuempel/Fiji_sewage/raw_data/Allen_Coral_Atlas/coral_algae.shp", delete_layer = T)


```

```{r}
sub_reef<-st_read("/home/kuempel/Fiji_sewage/raw_data/Allen_Coral_Atlas/coral_algae.shp")

sub_reef<-st_make_valid(sub_reef)

reef_proj<-st_transform(sub_reef, t_crs)

tik<-st_read(here("projected_data/Tikina/Fiji_tikina.shp")) %>% 
  st_transform(., crs = t_crs)

plume<-raster(here("output_data/Plumes/All_plumes_fiji.tif")) %>% 
  projectRaster(., crs = t_crs)

reef_crop<-st_crop(reef_proj, plume)

st_write(reef_crop,here("projected_data/Allen_Coral_Atlas/coral_algae_crop.shp"), delete_layer = T)
```

