---
title: "Untitled"
author: "Caitie"
date: "2022-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(raster)
library(here)
library(ggplot2)
library(devtools)
library(patchwork)
library(viridis)
library(ggrepel)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

```{r}
n_septic_sens<-read.csv(here("output_data/Sensitivity/Septic_treatment_leach_buffer_analysis.csv")) %>% 
   dplyr::select(buffer, N) %>% 
  rename(Sept_N = N) %>% 
  unique() %>% 
  filter(!buffer %in% c(10,20,30,40,50))

coastal_n_septic<-read.csv(here("output_data/Sensitivity/Coastal_septic_treatment_leach_buffer_analysis.csv")) %>% 
  dplyr::select(buffer, N) %>% 
  rename(Coast_N = N) %>% 
  unique() %>% 
  filter(!buffer %in% c(10,20,30,40,50))

all_septic<-full_join(n_septic_sens, coastal_n_septic) %>% 
  mutate(Coast_N = ifelse(is.na(Coast_N) == T, 0, Coast_N),
         N_total = Sept_N + Coast_N)

n_rm_df<-data.frame(buffer = rep(seq(5,55, by = 10),each = 11), n_rm = rep(seq(0,1, 0.1),6))
n_rm_df2<-data.frame(buffer = rep(seq(100,500, by = 100), each = 11), n_rm = seq(0,1, 0.1))

all_nrm<-rbind(n_rm_df, n_rm_df2)

all_septic<-full_join(all_nrm, all_septic, by = c("buffer"))

all_septic2<-all_septic %>% 
  mutate(N_final = N_total * n_rm,
          z = ifelse(buffer == 35 & n_rm == 0.8, TRUE, FALSE),
         n_rm2 = 1-n_rm)
```


```{r}
n_septic_heatmap <- ggplot(data = all_septic2, mapping = aes(x = as.factor(n_rm2*100),
                                                       y = as.factor(buffer))) +
  geom_tile(aes(fill = N_final*0.001)) +
  geom_text(aes(label = round(N_final*0.001, 2), color=as.factor(z))) +
  scale_color_manual(guide = "none", values = c(`TRUE` = "red", `FALSE` = "black")) +
  xlab(label = "Nutrient removal (%)") + 
  ylab(label = "Buffer (m)") + 
  theme_bw() + 
  labs(fill="Nitrogen", title = "Septic") + 
  scale_fill_viridis(discrete=FALSE, direction=-1) +
  theme(plot.title = element_text(hjust = 0.5))
  

n_septic_heatmap
```
```{r}
ggsave(here("figures/Supp_N_septic_treat_buffer_sensitivity_heatmap.png"), dpi =300, width = 8, height = 6)
```

```{r}
n_other_sens<-read.csv(here("output_data/Sensitivity/Direct_treatment_leach_buffer_analysis.csv")) %>% 
   dplyr::select(buffer, N) %>% 
  rename(Other_N = N) %>% 
  unique() %>% 
  filter(!buffer %in% c(10,20,30,40,50))

coastal_n_other<-read.csv(here("output_data/Sensitivity/Coastal_direct_treatment_leach_buffer_analysis.csv")) %>% 
  dplyr::select(buffer, N) %>% 
  rename(Coast_N = N) %>% 
  unique() %>% 
  filter(!buffer %in% c(10,20,30,40,50))

all_other<-full_join(n_other_sens, coastal_n_other) %>% 
  mutate(Coast_N = ifelse(is.na(Coast_N) == T, 0, Coast_N),
         N_total = Other_N + Coast_N)


all_other<-full_join(all_nrm, all_other, by = c("buffer"))

all_other2<-all_other %>% 
  mutate(N_final = N_total * n_rm,
          z = ifelse(buffer == 35 & n_rm == 0.2, TRUE, FALSE),
         n_rm2 = 1-n_rm)
```



```{r}
n_other_heatmap <- ggplot(data = all_other2, mapping = aes(x = as.factor(n_rm2*100),
                                                       y = as.factor(buffer))) +
  geom_tile(aes(fill = N_final*0.001)) +
  geom_text(aes(label = round(N_final*0.001, 2), color=as.factor(z))) +
  scale_color_manual(guide = "none", values = c(`TRUE` = "red", `FALSE` = "black")) +
  xlab(label = "Nutrient removal (%)") + 
  ylab(label = "Buffer (m)") + 
  theme_bw() + 
  labs(fill="Nitrogen", title = "Other") + 
  scale_fill_viridis(discrete=FALSE, direction=-1) +
  theme(plot.title = element_text(hjust = 0.5)) 
  
  

n_other_heatmap
```
```{r}
ggsave(here("figures/Supp_N_other_treat_buffer_sensitivity_heatmap.png"), dpi =300, width = 8, height = 6)
```

# Combine

```{r}
combined <- n_other_heatmap + n_septic_heatmap & theme(legend.position = "bottom")
combined + plot_layout(guides = "collect")
```


# Phosphorus


```{r}
p_septic_sens<-read.csv(here("output_data/Sensitivity/Septic_treatment_leach_buffer_analysis.csv")) %>% 
   dplyr::select(buffer, P) %>% 
  rename(Sept_P = P) %>% 
  unique() %>% 
  filter(!buffer %in% c(10,20,30,40,50))

coastal_p_septic<-read.csv(here("output_data/Sensitivity/Coastal_septic_treatment_leach_buffer_analysis.csv")) %>% 
  dplyr::select(buffer, P) %>% 
  rename(Coast_P = P) %>% 
  unique() %>% 
  filter(!buffer %in% c(10,20,30,40,50))

all_septic_p<-full_join(p_septic_sens, coastal_p_septic) %>% 
  mutate(Coast_P = ifelse(is.na(Coast_P) == T, 0, Coast_P),
         P_total = Sept_P + Coast_P)


all_septic_p<-full_join(all_nrm, all_septic_p, by = c("buffer"))

all_septic_p2<-all_septic_p %>% 
  mutate(P_final = P_total * n_rm,
          z = ifelse(buffer == 35 & round(n_rm,1) == 0.7, TRUE, FALSE),
         n_rm2 = 1-n_rm)
```

```{r}
p_septic_heatmap <- ggplot(data = all_septic_p2, mapping = aes(x = as.factor(n_rm2*100),
                                                       y = as.factor(buffer))) +
  geom_tile(aes(fill = P_final*0.001)) +
  geom_text(aes(label = round(P_final*0.001, 2), color=as.factor(z))) +
  scale_color_manual(guide = "none", values = c(`TRUE` = "red", `FALSE` = "black")) +
  xlab(label = "Nutrient removal (%)") + 
  ylab(label = "Buffer (m)") + 
  theme_bw() + 
  labs(fill="Phosphorus", title = "Septic") + 
  scale_fill_viridis(discrete=FALSE, direction=-1) +
  theme(plot.title = element_text(hjust = 0.5))
  

p_septic_heatmap
```


```{r}
p_other_sens<-read.csv(here("output_data/Sensitivity/Direct_treatment_leach_buffer_analysis.csv")) %>% 
   dplyr::select(buffer, P) %>% 
  rename(Other_P = P) %>% 
  unique() %>% 
  filter(!buffer %in% c(10,20,30,40,50))

coastal_p_other<-read.csv(here("output_data/Sensitivity/Coastal_direct_treatment_leach_buffer_analysis.csv")) %>% 
  dplyr::select(buffer, P) %>% 
  rename(Coast_P = P) %>% 
  unique() %>% 
  filter(!buffer %in% c(10,20,30,40,50))

all_other_p<-full_join(p_other_sens, coastal_p_other) %>% 
  mutate(Coast_P = ifelse(is.na(Coast_P) == T, 0, Coast_P),
         P_total = Other_P + Coast_P)


all_other_p<-full_join(all_nrm, all_other_p, by = c("buffer"))

all_other_p2<-all_other_p %>% 
  mutate(P_final = P_total * n_rm,
          z = ifelse(buffer == 35 & round(n_rm,1) == 0.1, TRUE, FALSE),
         n_rm2 = 1-n_rm)
```

```{r}
p_other_heatmap <- ggplot(data = all_other_p2, mapping = aes(x = as.factor(n_rm2*100),
                                                       y = as.factor(buffer))) +
  geom_tile(aes(fill = P_final*0.001)) +
  geom_text(aes(label = round(P_final*0.001, 2), color=as.factor(z))) +
  scale_color_manual(guide = "none", values = c(`TRUE` = "red", `FALSE` = "black")) +
  xlab(label = "Nutrient removal (%)") + 
  ylab(label = "Buffer (m)") + 
  theme_bw() + 
  labs(fill="Phosphorus", title = "Other") + 
  scale_fill_viridis(discrete=FALSE, direction=-1) +
  theme(plot.title = element_text(hjust = 0.5))
  

p_other_heatmap
```
