---
title: "Untitled"
author: "Caitie"
date: "2022-07-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(nngeo)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

# Coral reef results

```{r}
reef_nutri<-st_read(here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs.shp")) %>% 
  st_transform(., t_crs) %>% 
  mutate(area_m2 = as.numeric(st_area(.)))
```



```{r}
sub_reef_nutri<-reef_nutri %>% 
   filter(n_reefs>0) %>% 
   mutate(n_reefs_tonnes = n_reefs*0.001)

sub_reef_nutri<- sub_reef_nutri %>% 
   arrange(desc(n_reefs_tonnes)) %>% 
   mutate(cumsum_n = cumsum(n_reefs_tonnes),
          prop = cumsum_n/sum(sub_reef_nutri$n_reefs_tonnes, na.rm = T))
 
 top_90<-sub_reef_nutri %>% 
   filter(prop <=0.9)
 
 nrow(top_90)
 
 reef_nutri_df<-sub_reef_nutri %>% 
   as.data.frame() %>% 
   dplyr::select(-geometry)
```

```{r}
sum(reef_nutri_df$n_reefs_tonnes,na.rm = T)
sum(reef_nutri_df$n_reefs_tonnes,na.rm = T)/365.7
```

```{r}
nrow(sub_reef_nutri)/nrow(reef_nutri)
```

```{r}
nrow(top_90)/nrow(sub_reef_nutri)
```

# Reef area affected 

```{r}
sum(sub_reef_nutri$area_m2, na.rm = T)*1e-6 #area with nutrients

sum(reef_nutri$area_m2, na.rm = T)*1e-6 # total reef area
```

```{r}
(sum(sub_reef_nutri$area_m2, na.rm = T)*1e-6)/(sum(reef_nutri$area_m2, na.rm = T)*1e-6)
```

# WWTP

```{r}
connected<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_connected_pourpoints.shp"))

```


```{r}
treatment<-st_read(here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs_by_treatment.shp")) %>% 
  mutate(prop = uncnn__/n_reefs)

sub_treatment<-treatment %>% 
  filter(n_reefs>0)

length(which(treatment$prop>0.5))/nrow(treatment)
```



```{r}
basin_dat<-st_read(here("output_data/Nutrients_at_pourpoints/All_nutrients_at_pourpoints.shp")) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) 

basin_n<- basin_dat %>% 
  group_by(MAIN_BAS) %>% 
  summarise(basin_N = sum(N, na.rm = T))

prop_conn<-basin_dat %>% 
  group_by(MAIN_BAS, type) %>% 
  summarise(basin_N_type = sum(N, na.rm = T)) %>% 
  mutate(basin_N_type2 =ifelse(is.na(basin_N_type) == T, 0, as.numeric(basin_N_type))) %>% 
  pivot_wider(., names_from = type, values_from = basin_N_type2) %>% 
  replace(is.na(.), 0) %>% 
  mutate(total = sum(Coastal_direct + Coastal_septic + Direct + Septic + Connected),
         prop_unconn = sum(Coastal_direct + Coastal_septic + Direct + Septic)/total)
```

```{r}
basin_plumes_dat<-st_read(here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs_by_basin.shp")) 

basin_plumes<-basin_plumes_dat %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  pivot_longer(., cols = c("X512008155":"X512008225"), names_to = "MAIN_BAS", values_to = "reef_N") %>% 
  group_by(MAIN_BAS) %>% 
  summarise(reef_N = sum(reef_N, na.rm = T)) %>% 
  mutate(MAIN_BAS = str_replace(MAIN_BAS, "X", ""),
         MAIN_BAS = str_pad(MAIN_BAS,side="right", width = 10, pad="0"),
         MAIN_BAS = as.numeric(MAIN_BAS))
```



```{r}
basin_reef_join<-full_join(basin_n, basin_plumes) %>% 
 # filter(!is.na(basin_N) == T,
#         basin_N>0) %>% 
  mutate(reef_N = ifelse(is.na(reef_N) == T, 0, reef_N),
         basin_N = ifelse(is.na(basin_N) == T, 0, basin_N),
         ratio = reef_N/basin_N) 
```
```{r}
cor.test(basin_reef_join$basin_N, basin_reef_join$reef_N, method = "pearson")

```

```{r}
basin_connected<-basin_reef_join %>% 
  filter(MAIN_BAS %in% connected$MAIN_BAS) %>% 
  full_join(., connected)
```

```{r}
cor.test(basin_connected$basin_N, basin_connected$reef_N, method = "pearson")
```

```{r}
n_basins_reef<-st_read(here("output_data/Nutrients_at_reefs/Number_watersheds_contributing_reef_nutrients.shp")) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) 

n_basins_reef<-n_basins_reef%>% 
  dplyr::select(id, n_reefs)

mean(n_basins_reef$n_reefs)

length(which(n_basins_reef$n_reefs>1))/nrow(n_basins_reef)
```

