---
title: "All_nutrients_pourpoints"
author: "Caitie"
date: "14/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(sf)
library(raster)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

# Read in data

## Connected 

```{r}
connected<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_connected_pourpoints.shp"))
st_crs(connected)<-t_crs

connected<-st_transform(connected, t_crs)

connected<-connected %>% 
  dplyr::select(N_final, P_final) %>% 
  rename(N = N_final,
         P = P_final) %>% 
  mutate(type = "Connected")
```


## Septic

```{r}
septic<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_septic_pourpoints.shp")) %>% 
  dplyr::select(N_leach, P_leach) %>% 
  rename(N = N_leach,
         P = P_leach) %>% 
  mutate(type = "Septic") %>% 
  st_transform(., t_crs)
st_crs(septic)<-t_crs
```


## Direct

```{r}
direct<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_direct_pourpoints.shp")) %>% 
  dplyr::select(N_leach, P_leach) %>% 
  rename(N = N_leach,
         P = P_leach) %>% 
  mutate(type = "Direct") %>% 
  st_transform(., t_crs)

st_crs(direct)<-t_crs
```

## Coastal

```{r}
coastal_septic<-st_read(here("output_data/Nutrients_at_pourpoints/Coastal_septic_pourpoints.shp")) %>% 
  dplyr::select(septic_N, septic_P) %>% 
  rename(N = septic_N,
         P = septic_P) %>% 
  mutate(type = "Coastal_septic") %>% 
  st_transform(., t_crs)

st_crs(coastal_septic)<-t_crs
```
```{r}
coastal_direct<-st_read(here("output_data/Nutrients_at_pourpoints/Coastal_direct_pourpoints.shp")) %>% 
  dplyr::select(direct_N, direct_P) %>% 
  rename(N = direct_N,
         P = direct_P) %>% 
  mutate(type = "Coastal_direct") %>% 
  st_transform(., t_crs)

st_crs(coastal_direct)<-t_crs
```

# Combine


```{r}
all<-rbind(connected, septic, direct, coastal_septic, coastal_direct)

all<-st_transform(all, t_crs)
```









```{r}
#unconnected<-st_join(direct,septic) %>% 
#  dplyr::select(-HYRIV_ID.y, -MAIN_BAS.y) %>% 
#  rename(HYRIV_ID = HYRIV_ID.x,
#         MAIN_BAS = MAIN_BAS.x) %>% 
 # mutate(un_N_leach = N_septic_leach + N_direct_leach,
#         un_P_leach = P_septic_leach + P_direct_leach) %>% 
#  dplyr::select(HYRIV_ID, N_septic_leach, N_direct_leach, P_septic_leach, #P_direct_leach) %>% 
#  rename(pourpoint =HYRIV_ID) %>% 
#  mutate(conn_N = NA,
#         conn_P = NA,
#         coastal_N = NA,
#         coastal_P = NA)
```

```{r}
#coastal<-rbind(coastal_septic, coastal_direct) #%>% 
#  mutate(coastal_N = N_coastal_septic + N_coastal_direct,
#         coastal_P = P_coastal_septic + P_coastal_direct) %>% 
#  rename(pourpoint = cellindex) %>% 
#  mutate(conn_N = NA,
#         conn_P = NA,
#         un_N_leach = NA,
#         un_P_leach = NA)
  
```


```{r}
#connected_final<-connected %>% 
#  dplyr::select(Name, N, P) %>% 
#  rename(pourpoint = Name,
#         conn_N = N,
#         conn_P = P) %>% 
#mutate(un_N_leach = NA,
#         un_P_leach = NA,
#         N_septic_leach = NA,
#         N_direct_leach = NA,
#         P_septic_leach = NA,
#         P_direct_leach = NA)

```


```{r}
#all_pp<-rbind(connected_final, unconnected_final)

#all_pp2<-st_transform(all_pp, t_crs)
```


# Write data - send data to Daniel for ocean transport model

```{r}
st_write(all, here("output_data/Nutrients_at_pourpoints/All_nutrients_at_pourpoints.shp"), delete_layer = T)
```

For some reason the CRS doesn't save...
```{r}
test<-st_read(here("output_data/Nutrients_at_pourpoints/All_nutrients_at_pourpoints.shp"))
```



