---
title: "Untitled"
author: "Caitie"
date: "25/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(here)
library(raster)
library(ggplot2)
library(rgdal)
library(gdistance)
library(reshape2)
library(rgrass7)
library(parallel)
library(tmap)
#remotes::install_github("SEEG-Oxford/seegSDM")
library(seegSDM)
library(tabularaster)
library(units)
library(lwgeom)

source(here("scripts/plume_functions.R"))
```

# Nutrients at each pourpoint

```{r}
stp_crs<-st_read(here("output_data/Sewage_plants/Nutrients_at_STP.shp"))

stp<-read.csv(here("output_data/Sewage_plants/Connected_tourist_nutrients.csv")) %>% 
  rename(N = Total_N,
         P = Total_P) %>% 
  mutate(ID = ifelse(Plant_Name == "Kinoya",3 ,
                     ifelse(Plant_Name == "Nadali",5 ,
                            ifelse(Plant_Name == "Namara",6,
                                   ifelse(Plant_Name == "Natabua", 7,
                                          ifelse(Plant_Name == "Navakai", 8,
                                                 ifelse(Plant_Name == "Olosara",9 ,
                                                        ifelse(Plant_Name == "Pacific Harbor",2 ,
                                                               ifelse(Plant_Name == "Votua", 10, NA)))))))))
```

# Location of pourpoints

```{r}
stp_pp<-st_read(here("output_data/Sewage_plants/All_STP_outfalls_Fiji.shp")) %>% 
    mutate(ID = ifelse(Name == "Pacific Harbor Sewage Outfall", 2,
                            ifelse(Name == "PWD (Kinoya) Sewage Outfall" , 3,
                                 #  ifelse(Name == "Naboro", 4,
                                   #       ifelse(Name == "Nadali", 5,
                                                 ifelse(Name ==  "Labasa Outfall", 6,
                                                        ifelse(Name == "Lautoka Natabua Sewage Outfall", 7,
                                                               ifelse(Name ==  "Nadi outfall" , 8,
                                                                      ifelse(Name == "Sigatoka Outfall", 9,
                                                                             ifelse(Name == "Ba outfall", 10, NA))))))))

stp_pp_proj<-st_transform(stp_pp, st_crs(stp_crs)) %>% 
  mutate(ID = ifelse(Name == "Rewa Outfall", 5, 
                     ifelse(Name == "ACS Outfall",1,
                            ifelse(Name == "Naboro Outfall", 4,
                                   ifelse(Name == "Wailada Outfall", 11, as.numeric(ID))))))

# Need to look into outfalls again
```


# Join pourpoints together and with nutrients

```{r}
pour_points<-full_join(stp_pp_proj, stp, by = "ID") %>% 
  rename(STP = Plant_Name) %>% 
  dplyr::select(Name, STP, ID, N, P) %>% 
  filter(!is.na(STP) == T)
```


# Diffusion model

Apply function to points list

```{r}
#ocean_raster<-raster(here("raw_data/Global/oceans_moll.tif"))

#ocean_raster<-projectRaster(ocean_raster, crs = as.character(crs(stp_pp_proj)))

#writeRaster(ocean_raster, here("projected_data/oceans_moll_proj.tif"))

ocean_raster<-raster(here("projected_data/oceans_moll_proj.tif"))
```


```{r}
p_extent=st_as_sfc(st_bbox(pour_points))
p_extent_sub = st_make_grid(p_extent,n = c(40,20)) %>%
               st_as_sf() %>% 
               rename(geom=x) %>%
               mutate(group=1:nrow(.))
tm_shape(p_extent_sub)+tm_polygons()
pour_points = st_join(pour_points, p_extent_sub, join = st_intersects) %>% 
              mutate(ID=1:nrow(.)) %>% 
  as_Spatial

  point_list<-split(pour_points,as.character(pour_points@data$ID))
  re = parallel::mclapply(point_list, N_plume, ocean_raster, 80000, c(1110,894), 90000, mc.cores = 10)
  
  # Set extent for all outputs to the max extent needed, e.g., newextent
  newextent<-extent(Reduce(extend,re)) # Get max extent of all objects
  re_ext=pbmclapply(re, extend, newextent, mc.cores=1, mc.style = "ETA") # Use fewer cores as this gets more memory heavy
  gc()
  
  # Reclass NAs to 0
  re_ext = mclapply(re_ext, mc.cores = 1, function(x) reclassify(x, cbind(NA,0))) # Reclass NA to 0, in a more memory friendly way,apparently...
  gc()

  # Add all rasters in the group together + mask out land areas is desired
  sed_plume_merge = Reduce("+", re_ext) 
  sed_plume_merge = sed_plume_merge * ocean_raster # mask out land; disregard the warning

  writeRaster(sed_plume_merge, here(paste0("output_data/Nutrients/Fiji_connected_tourism_N_plumes.tif")), overwrite = TRUE, options=c("compress=deflate","tiled=yes","num_threads=6")) 
```

```{r}
  re = mclapply(point_list, P_plume, ocean_raster, 80000, c(1110,894), 90000, mc.cores = 10)
  
  # Set extent for all outputs to the max extent needed, e.g., newextent
  newextent<-extent(Reduce(extend,re)) # Get max extent of all objects
  re_ext=mclapply(re, extend, newextent, mc.cores=1) # Use fewer cores as this gets more memory heavy
  gc()
  
  # Reclass NAs to 0
  re_ext = mclapply(re_ext, mc.cores = 1, function(x) reclassify(x, cbind(NA,0))) # Reclass NA to 0, in a more memory friendly way,apparently...
  gc()

  # Add all rasters in the group together + mask out land areas is desired
  sed_plume_merge = Reduce("+", re_ext) 
  sed_plume_merge = sed_plume_merge * ocean_raster # mask out land; disregard the warning

  writeRaster(sed_plume_merge, here("output_data/Nutrients/Fiji_connected_tourism_P_plumes.tif"), overwrite = TRUE, options=c("compress=deflate","tiled=yes","num_threads=6")) 


```
