---
title: "Untitled"
author: "Caitie"
date: "29/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(raster)
library(here)
library(sf)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

## Tourism

Total tourists

```{r}
visit_arrivals<-read_csv(here("raw_data/Tourism/Fiji_Visitor_Arrivals_by_Country.csv")) %>% 
  dplyr::select(Year, Month, Country, Visitor_arrivals) %>% 
  filter(!Country == "Total") %>% 
  group_by(Country) %>% 
  summarise(Total_vistors = sum(Visitor_arrivals, na.rm = T)) %>% 
  mutate(Country = ifelse(Country == "Korea", "South Korea", as.character(Country)))

sum(visit_arrivals$Total_vistors)
```


```{r}
tik_hotels<-st_read(here("output_data/Tourism/Final_hotel_room_map.shp"))
#tik_hotels<-st_read(here("output_data/Tourism/All_hotels_by_tikina.csv"))

#total number of hotels 
nrow(tik_hotels)

tik_hotels_treatment<-read.csv(here("output_data/Tourism/Hotels_treatment_type.csv"))

nrow(tik_hotels_treatment)
length(unique(tik_hotels_treatment$Name))
nrow(tik_hotels_treatment)/nrow(tik_hotels)

test<-tik_hotels_treatment %>% 
  filter(!is.na(Total_rooms) == T)

test2<-tik_hotels_treatment %>% 
  filter(is.na(Total_rooms) == T)

nrow(test)
length(unique(test$Name))

length(unique(test$Name))/length(unique(tik_hotels_treatment$Name))

```

```{r}
length(which(tik_hotels_treatment$treatment_level == "Secondary"))
length(which(tik_hotels_treatment$treatment_level == "Primary"))
length(which(tik_hotels_treatment$treatment_level == "Septic"))
```

```{r}
# Relationship between # visitors and # hotels in a Tikina

prop_occupancy_tik<-read.csv(here("tables/Hotels_rooms_visitors_Fiji.csv"))

cor.test(prop_occupancy_tik$Tik_visitors, prop_occupancy_tik$Num_hotels, method = "pearson")
cor.test(prop_occupancy_tik$Prop_visitors, prop_occupancy_tik$Prop_hotels, method = "pearson")

```

```{r}
tik_tourist_nutrients<-read.csv(here("output_data/Tourism/Tourist_nutrients_by_Tikina.csv"))

tourist_n<-sum(tik_tourist_nutrients$Tourist_N, na.rm = T)* 0.001
tourist_p<-sum(tik_tourist_nutrients$Tourist_P, na.rm = T)* 0.001

tourist_n
tourist_p

```
```{r}
# Nutrients after treatment
tourist_treated<-read.csv(here("output_data/Tourism/Treated_tourist_nutrients.csv"))

tourist_n_treat<-sum(tourist_treated$Treated_N, na.rm = T)*0.001
tourist_p_treat<-sum(tourist_treated$Treated_P, na.rm = T)*0.001

tourist_n_treat
tourist_p_treat
```

```{r}
# Total nutrient removal rate (Raw-Final)/Raw
(tourist_n - tourist_n_treat)/tourist_n # N removal
(tourist_p- tourist_p_treat)/tourist_p # P removal

```

```{r}
# Percentage of total nutrients that Tourism makes up
tourist_n_treat/(367.8306 + tourist_n_treat)

tourist_p_treat/(56.63899 + tourist_p_treat)
```

```{r}
tourist_treated %>%
  group_by(treatment_level) %>% 
  summarise(total_N = sum(Treated_N, na.rm = T),
            total_P = sum(Treated_P, na.rm = T))
```

Values if leaching is added to septic
```{r}
septic_tourist_treated<-tourist_treated %>% 
  filter(treatment_level == "Septic")
```

```{r}
area_tourist_nutrients<-tourist_treated %>% 
  group_by(Area.1) %>% 
  summarise(tourist_N = sum(Tourist_N, na.rm = T),
            tourist_P = sum(Tourist_P, na.rm = T),
            treat_N = sum(Treated_N, na.rm = T),
            treat_P = sum(Treated_P, na.rm = T)) %>% 
  mutate(All_nutrients = treat_N + treat_P)


area_tourist_nutrients
```


```{r}
23502.9/sum(area_tourist_nutrients$treat_N, na.rm = T)
```

