---
title: "Untitled"
author: "Caitie"
date: "2022-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(raster)
library(here)
library(ggplot2)
library(devtools)
library(patchwork)
library(viridis)
library(ggrepel)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

```{r}
septic_n<-read_csv(here("output_data/Sensitivity/All_septic_nitrogen_treatment_buffer.csv")) %>% 
  dplyr::select(n_rm, buffer, N_final) %>% 
  rename(Total = N_final) %>% 
  mutate(Nutrient = "Nitrogen")
septic_p<-read_csv(here("output_data/Sensitivity/All_septic_phosphorus_treatment_buffer.csv")) %>% 
  dplyr::select(n_rm, buffer, P_final) %>% 
  rename(Total = P_final) %>% 
  mutate(Nutrient = "Phosphorus")
other_n<-read_csv(here("output_data/Sensitivity/All_other_nitrogen_treatment_buffer.csv"))%>% 
  dplyr::select(n_rm, buffer, N_final) %>% 
  rename(Total = N_final) %>% 
  mutate(Nutrient = "Nitrogen")
other_p<-read_csv(here("output_data/Sensitivity/All_other_phosphorus_treatment_buffer.csv")) %>% 
  dplyr::select(n_rm, buffer, P_final) %>% 
  rename(Total = P_final) %>% 
  mutate(Nutrient = "Phosphorus")
```

```{r}
septic<-rbind(septic_n, septic_p)
other<-rbind(other_n, other_p)
```

```{r}
septic_35<-septic %>% 
  filter(buffer == 35) %>% 
  mutate(type = "Septic")

other_35<-other %>% 
  filter(buffer == 35) %>% 
  mutate(type = "Other")

#Septic N = 20-80
#Septic P = 30-100

#Other N = 80-98%
#Other P = 99%

all<-rbind(septic_35, other_35) %>% 
  mutate(Removal = ifelse(type == "Septic" & Nutrient == "Nitrogen" & n_rm == 0.8, "Lower",
                         ifelse(type == "Septic" & Nutrient == "Phosphorus" & n_rm == 0.7, "Lower", 
                                ifelse(type == "Other" & Nutrient == "Nitrogen" & n_rm == 0.2, "Lower", 
                                       ifelse(type == "Other" & Nutrient == "Phosphorus" & n_rm == 0, "Lower",
                                              ifelse(type == "Septic" & Nutrient == "Nitrogen" & n_rm == 0.2, "Upper",
                                                     ifelse(type == "Septic" & Nutrient == "Phosphorus" & n_rm == 0, "Upper", 
                                                            ifelse(type == "Other" & Nutrient == "Nitrogen" & n_rm == 0, "Upper", 
                                                                   ifelse(type == "Other" & Nutrient == "Phosphorus" & n_rm == 0, "Upper", NA)))))))))


sub<-all %>% 
  filter(Removal %in% c("Upper", "Lower"))
```

# Adjust values to match those of MS



```{r}
#all2<-all %>% 
#  mutate(Total_adj = ifelse(Nutrient == "Nitrogen" & type == "Septic" & n_rm >0.8, NA, as.numeric(Total)),
 #        Total_adj = ifelse(Nutrient == "Nitrogen" & type == "Septic" & n_rm <0.2, NA, as.numeric(Total_adj)),
 #        Total_adj = ifelse(Nutrient == "Phosphorus" & type == "Septic" & n_rm >0.7, NA, as.numeric(Total_adj)),
 #        Total_adj = ifelse(Nutrient == "Phosphorus" & type == "Septic" & n_rm <0.3, NA, as.numeric(Total_adj)),
 #        Total_adj = ifelse(Nutrient == "Nitrogen" & type == "Other" & n_rm <0.2, NA, as.numeric(Total_adj)),
 #        Total_adj = ifelse(Nutrient == "Phosphorus" & type == "Other" & n_rm !=0, NA, as.numeric(Total_adj)))

#sub2<-all2 %>% 
#  filter(points == "yes")
```

```{r}
ggplot(all, aes(x = (1-n_rm)*100, y = Total*0.001, col = Nutrient)) +
  geom_line() +
  geom_point(data = sub, aes(x = (1-n_rm)*100, y = Total*0.001, shape = Removal), size = 4)+
  facet_grid(~type, scales = "free") +
  theme_bw() +
  ylab("Nutrient load\n(tonnes)") +
  xlab("Nutrient removal rate (%)") +
  scale_x_continuous(breaks=seq(0,100,20))
```

```{r}
ggsave(here("figures/Figure3_nutrient_removal_sensitivity.png"), dpi = 300, width = 6, height = 3)
```

