---
title: "Untitled"
author: "Caitie"
date: "16/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(leaflet)
library(shiny)
library(tmap)
library(here)
library(sf)
library(tidyverse)
library(nngeo)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

# Fiji basins/Fiji outline

```{r}
fiji_basins12<-st_read(here("projected_data/Basins/Fiji_basins12.shp")) %>% 
  filter(!MAIN_BAS %in% c(5120082250)) 

fiji_basins<-st_transform(fiji_basins12, t_crs) %>% 
  dplyr::select(MAIN_BAS, area_km2) %>% 
  group_by(MAIN_BAS) %>% 
  summarise(total_area = sum(area_km2, na.rm = T))
```
```{r}
test<-st_read(here("raw_data/Tikina/fji_polbnda_adm3_tikina.shp")) %>% 
  st_transform(., t_crs) 

test2<-st_intersection(test, fiji_basins) 

test3<-test2%>% 
  mutate(div_basin_area = as.numeric(st_area(.))) %>% 
  group_by(ADM1_NAME, MAIN_BAS) %>% 
  summarise(div_basin_area = sum(div_basin_area,na.rm = T)) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry)

fiji_basin_div<-full_join(fiji_basins, test3, by = "MAIN_BAS") %>% 
  mutate(prop = (div_basin_area*1e-6)/total_area) %>% 
  group_by(MAIN_BAS) %>% 
    filter(prop == max(prop))
```

# Unconnected

```{r}
septic<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_septic_pourpoints.shp")) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  group_by(MAIN_BA) %>% 
  summarise(total_N_tonnes = sum(N, na.rm = T)*0.001,
            total_P_tonnes = sum(P, na.rm = T)*0.001) %>% 
  rename(MAIN_BAS = MAIN_BA)
```

```{r}
direct<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_direct_pourpoints.shp")) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  group_by(MAIN_BA) %>% 
  summarise(total_N_tonnes = sum(N, na.rm = T)*0.001,
            total_P_tonnes = sum(P, na.rm = T)*0.001) %>% 
  rename(MAIN_BAS = MAIN_BA)
```
# Combine with basin shapefile

```{r}
septic_nutri_basin<-full_join(fiji_basins, septic, by = "MAIN_BAS")

septic_nutri_basin2<-septic_nutri_basin %>% 
  mutate(total_N_tonnes = as.numeric(total_N_tonnes),
         total_N_tonnes = ifelse(is.na(total_N_tonnes) == T, 0, as.numeric(total_N_tonnes)))
```

```{r}
direct_nutri_basin<-full_join(fiji_basins, direct, by = "MAIN_BAS")

direct_nutri_basin2<-direct_nutri_basin %>% 
  mutate(total_N_tonnes = as.numeric(total_N_tonnes),
         total_N_tonnes = ifelse(is.na(total_N_tonnes) == T, 0, as.numeric(total_N_tonnes)))
```


# Plot
```{r}
septic_nutri<-tm_shape(septic_nutri_basin2) +
    tm_polygons(col = "total_N_tonnes",
                style = "cont",
                title = "Nitrogen\n(tonnes)",
                palette = "-viridis") +
  tm_layout(title = "Septic",
            title.position = c("center", "TOP")) 

septic_nutri
```

```{r}
direct_nutri<-tm_shape(direct_nutri_basin2) +
    tm_polygons(col = "total_N_tonnes",
                style = "cont",
                title = "Nitrogen\n(tonnes)",
                palette = "-viridis") +
  tm_layout(title = "Other",
            title.position = c("center", "TOP")) +
  tm_scale_bar() 

direct_nutri
```

# Connected

```{r}
connected<-st_read(here("output_data/Nutrients_at_pourpoints/Fiji_connected_pourpoints.shp")) %>% 
  mutate(N_tonnes = N_final*0.001) %>% 
  arrange(N_tonnes) %>% 
  mutate(label = str_remove(STP_x, " WWTP"),
         label = ifelse(label == "Natabua", "Lautoka",
                        ifelse(label == "Namara TP", "Namara", label)))

```


```{r}
basins_diss<-fiji_basins %>% 
  mutate(ID = as.numeric(1)) %>% 
  group_by(ID) %>% 
  summarise(total_area_km2 = sum(total_area, na.rm = T))
```


```{r}
connected_nutri_plot<-tm_shape(basins_diss) +
  tm_borders() +
  tm_shape(connected)+
  tm_bubbles(col = "N_tonnes",
             style = "cont",
             size = 0.5,
             border.col = "black", 
             border.lwd = 2, 
             title.shape = "Nitrogen\n(tonnes)", 
             title.col = "Nitrogen\n(tonnes)",
             palette = "-viridis") +
  tm_text("label",
          auto.placement = 1, 
          size = 1) +
  tm_layout(title = "Connected",
            title.position = c("center", "TOP")) #+
  #tm_text("label", size = 1, auto.placement = 1.5, col = "darkblue")

connected_nutri_plot
```
# Tourism

```{r}
tourist<-read.csv(here("output_data/Tourism/Treated_tourist_nutrients.csv")) %>% 
  group_by(MAIN_BAS) %>% 
  summarise(total_N_tonnes = sum(Treated_N, na.rm = T)*0.001,
            total_P_tonnes = sum(Treated_P, na.rm = T)*0.001)
```

```{r}
basin_tourism<-full_join(fiji_basins, tourist, by = "MAIN_BAS")
```

```{r}
tourism_nutri<-tm_shape(basin_tourism) +
    tm_polygons(col = "total_N_tonnes",
                style = "cont",
                title = "Nitrogen\n(tonnes)",
                palette = "-viridis") +
  tm_layout(title = "Tourism",
            title.position = c("center", "TOP")) +
  tm_scale_bar()

tourism_nutri
```
```{r}
tmap_save(tourism_nutri, here("figures/Nutrient_tourism_treatment_map.png"), dpi = 300, width = 10, height = 5)
```

# All together

```{r}
nutri_final<-tmap_arrange(direct_nutri, septic_nutri, connected_nutri_plot, nrow = 1)

nutri_final
```

```{r}
tmap_save(nutri_final, here("figures/Nutrient_residential_treatment_map.png"), dpi = 300, width = 15, height = 5)
```


```{r}
#nutri_final_all<-tmap_arrange(direct_nutri, septic_nutri, connected_nutri_plot, tourism_nutri, nrow = 1)

#nutri_final_all
```

```{r}
#tmap_save(nutri_final_all, here("figures/Nutrient_all_treatment_map.png"), dpi = 300, width = 10, height = 5)
```

```{r}
basin_tourism_df<-basin_tourism %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  pivot_longer(., cols = c("total_N_tonnes","total_P_tonnes"), values_to= "Effluent", names_to = "Nutrient") %>% 
  mutate(type = "tourism")

septic_nutri_df<- septic_nutri_basin2 %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  pivot_longer(., cols = c("total_N_tonnes","total_P_tonnes"), values_to= "Effluent", names_to = "Nutrient") %>% 
  mutate(type = "septic")

direct_nutri_df<-direct_nutri_basin2 %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  pivot_longer(., cols = c("total_N_tonnes","total_P_tonnes"), values_to= "Effluent", names_to = "Nutrient") %>% 
  mutate(type = "direct")

sept_direct_tourism<-rbind(septic_nutri_df, direct_nutri_df, basin_tourism_df) %>% 
  dplyr::select(-total_area)
```

```{r}
fiji_basin_proj<-fiji_basins12 %>% 
  st_transform(., t_crs) %>% 
  dplyr::select(MAIN_BAS)

fiji_basin_df<-fiji_basin_proj %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry)

conn_dist<-st_nn(connected, fiji_basin_proj, k = 1, parallel = 10) %>% 
   unlist() 

bas_id<-fiji_basin_df[conn_dist,] %>% 
  as.data.frame() %>% 
  rename(MAIN_BAS = ".")

conn_basin2<-cbind(connected, bas_id) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  dplyr::select(N_final, P_final, MAIN_BAS) %>% 
  mutate(total_N_tonnes = N_final *0.001,
         total_P_tonnes = P_final * 0.001) %>% 
  dplyr::select(-N_final, -P_final) %>% 
  pivot_longer(., cols = c("total_N_tonnes","total_P_tonnes"), values_to= "Effluent", names_to = "Nutrient") %>% 
  mutate(type = "connected")

all<-rbind(conn_basin2, sept_direct_tourism)

write.csv(all, here("output_data/Results/Nutrient_results_by_basin.csv"))
```

# Phosphorus

```{r}
septic_nutri_p<-tm_shape(septic_nutri_basin2) +
    tm_polygons(col = "total_P_tonnes",
                style = "cont",
                title = "Phosphorus\n(tonnes)",
                palette = "-viridis") +
  tm_layout(title = "Septic",
            title.position = c("center", "TOP"))

septic_nutri_p
```

```{r}
direct_nutri_p<-tm_shape(direct_nutri_basin2) +
    tm_polygons(col = "total_P_tonnes",
                style = "cont",
                title = "Phosphorus\n(tonnes)",
                palette = "-viridis") +
  tm_layout(title = "Other",
            title.position = c("center", "TOP"))  +
  tm_scale_bar()

direct_nutri_p
```

```{r}
connected<-connected %>% 
  mutate(P_tonnes = P_final*0.001)

connected_nutri_plot_p<-tm_shape(basins_diss) +
  tm_borders() +
  tm_shape(connected)+
  tm_bubbles(col = "P_tonnes",
             style = "cont",
             size = 0.5,
             border.col = "black", 
             border.lwd = 2, 
             title.shape = "Nitrogen\n(tonnes)", 
             title.col = "Phosphorus\n(tonnes)",
             palette = "-viridis") +
  tm_layout(title = "Connected",
            title.position = c("center", "TOP")) #+
  #tm_text("label", size = 1, auto.placement = 1.5, col = "darkblue")

connected_nutri_plot_p
```

```{r}
tourism_nutri_p<-tm_shape(basin_tourism) +
    tm_polygons(col = "total_P_tonnes",
                style = "cont",
                title = "Phosphorus\n(tonnes)",
                palette = "-viridis") +
  tm_layout(title = "Tourism",
            title.position = c("center", "TOP")) 

tourism_nutri_p
```
```{r}
tmap_save(tourism_nutri_p, here("figures/Nutrient_tourism_treatment_phos_map.png"), dpi = 300, width = 10, height = 5)
```

```{r}
nutri_final_all_p<-tmap_arrange(direct_nutri_p, septic_nutri_p, connected_nutri_plot_p, tourism_nutri_p, nrow = 1)

nutri_final_all_p
```

```{r}
tmap_save(nutri_final_all_p, here("figures/Supp_nutrient_all_treatment_map_phosphorus.png"), dpi = 300, width = 10, height = 5)
```

```{r}
nutri_final_p<-tmap_arrange(direct_nutri_p, septic_nutri_p, connected_nutri_plot_p, nrow = 1)

nutri_final_p
```
```{r}
tmap_save(nutri_final_p, here("figures/Nutrient_residential_treatment_phosphorus_map.png"), dpi = 300, width = 10, height = 5)
```