---
title: "Untitled"
author: "Caitie"
date: "16/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(patchwork)
library(here)
library(viridis)
```

```{r}
nutri<-read.csv(here("output_data/Results/Nutrient_results.csv")) %>% 
  mutate(Type = ifelse(Type == "Direct", "Other", Type))
```

```{r}
nutri2<- nutri %>% 
  mutate(type2 = ifelse(Type == "Coastal_septic", "Septic",
         ifelse(Type == "Coastal_direct", "Other",
                ifelse(Type == "Tourism_primary", "Tourism",
                       ifelse(Type == "Tourism_secondary", "Tourism",
                              ifelse(Type == "Tourism_septic", "Tourism", as.character(Type)))))))
```

```{r}
nutri_dat<-nutri2 %>% 
  group_by(type2, Nutrient) %>% 
  summarise(Excreted= sum(Excreted),
            Effluent = sum(Effluent))

N_dat<-nutri_dat %>% 
  filter(Nutrient == "N")

P_dat<-nutri_dat %>% 
  filter(Nutrient == "P")

total_N = sum(N_dat$Effluent)
total_P = sum(P_dat$Effluent)

nutri_dat<-nutri_dat %>% 
  mutate(prop = ifelse(Nutrient == "N", Effluent/total_N, Effluent/total_P))

test<-nutri_dat %>% 
  filter(Nutrient == "N")

sum(test$prop)
```

```{r}
tonnes_bar<-ggplot(nutri_dat, aes(x = Nutrient, y = Effluent, fill = type2)) +
  geom_bar(position = "stack", stat = "identity") +
  theme_minimal() +
  theme(legend.position="none") +
  ylab("Nutrient load\n(tonnes)") +
  scale_fill_viridis_d()
  #scale_fill_manual(values = c("darkred","darkgoldenrod1", "darkorange2", "tan4")) #+
#  labs(fill = "Source")

tonnes_bar
```

```{r}
prop_bar<-ggplot(nutri_dat, aes(x = Nutrient, y = prop, fill = type2)) +
  geom_bar(position = "stack", stat = "identity") +
  theme_minimal() +
  scale_fill_viridis_d() +
  #scale_fill_manual(values = c("darkred","darkgoldenrod1", "darkorange2", "tan4"))+
  ylab("Proportion") +
  labs(fill = "Source")

prop_bar
```

```{r}
tonnes_bar + prop_bar
```

```{r}
ggsave(here("figures/Treatment_nutrients_bar_chart.png"), width = 10, height = 5, dpi = 300)
```

```{r}
nutri_dat2<-nutri_dat %>% 
  filter(!type2 == "Tourism")

tonnes_bar2<-ggplot(nutri_dat2, aes(x = Nutrient, y = Effluent, fill = type2)) +
  geom_bar(position = "stack", stat = "identity") +
  theme_minimal() +
 # theme(legend.position="none") +
  ylab("Nutrient load\n(tonnes)") +
  scale_fill_viridis_d() +
  coord_flip() +
  labs(fill = "Source")
  #scale_fill_manual(values = c("darkred","darkgoldenrod1", "darkorange2", "tan4")) #+
#  labs(fill = "Source")

tonnes_bar2
```
```{r}
ggsave(here("figures/Residential_treatment_nutrients_bar_chart.png"), width = 6, height = 3, dpi = 300)
```

```{r}

total_N2<-N_dat %>% 
  filter(!type2 == "Tourism") 

total_P2 = P_dat %>% 
  filter(!type2 == "Tourism") 

total_N3<-sum(total_N2$Effluent)

total_P3<-sum(total_P2$Effluent)

nutri_dat2 <- nutri_dat2 %>% 
  mutate(prop2 = ifelse(Nutrient == "N", Effluent/total_N3, Effluent/total_P3))

prop_bar2<-ggplot(nutri_dat2, aes(x = Nutrient, y = prop2, fill = type2)) +
  geom_bar(position = "stack", stat = "identity") +
  theme_minimal() +
  scale_fill_viridis_d() +
  #scale_fill_manual(values = c("darkred","darkgoldenrod1", "darkorange2", "tan4"))+
  ylab("Proportion") +
  labs(fill = "Source")

prop_bar2
```