---
title: "Untitled"
author: "Caitie"
date: "2022-07-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(ggplot2)
library(viridis)
library(ggExtra)
library(cowplot)
library(fasterize)
library(raster)
library(nngeo)
library(tmap)
library(here)
library(stars)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```


# Fiji

```{r}
fiji_basins12<-st_read(here("projected_data/Basins/Fiji_basins12.shp")) %>% 
  filter(!MAIN_BAS %in% c(5120082250)) %>% 
  mutate(dissolve = 1) %>% 
  group_by(dissolve) %>% 
  summarise(total_area = sum(area_km2, na.rm = T))  %>% 
  st_transform(., t_crs)
```


## Total

```{r}
reef_nutri_treat<-st_read(here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs_by_treatment.shp")) %>% 
  st_transform(., t_crs) %>% 
  mutate(area_m2 = as.numeric(st_area(.)),
         check_total = cnn_n_r + uncnn__,
         test = round(n_reefs, 5) == round(check_total, 5))

cent_treat<-st_centroid(reef_nutri_treat) 

treat_plot_dat<-st_coordinates(cent_treat)

treat_plot_dat2<- reef_nutri_treat %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  cbind(., treat_plot_dat)
  
```

```{r}
total_ras<-raster(here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs.tif"))
conn_ras<-raster(here("output_data/Nutrients_at_reefs/Connected_nitrogen_on_reefs.tif"))
unconn_ras<-raster(here("output_data/Nutrients_at_reefs/Unconnected_nitrogen_on_reefs.tif"))
```

```{r}
total_stars<-st_as_stars(total_ras)
total_sf<-st_as_sf(total_stars)
total_points<-st_centroid(total_sf) %>% 
  arrange(Nitrogen_on_reefs) %>% 
  filter(Nitrogen_on_reefs>0)

title_exp <- expression("Kg/km"^2)

breaks<-c(1,10,100,500,980)

p2<-ggplot(data = fiji_basins12) +
  geom_sf(fill = "grey") +
  #geom_sf_text(aes(label = TIKINA), colour = "black") +
  #geom_label_repel(aes(label = TIKINA, geometry = geometry),
  #  stat = "sf_coordinates") +
  geom_sf(data = total_points, aes(size = Nitrogen_on_reefs, color = Nitrogen_on_reefs)) +
  #geom_point(data = treat_plot_dat2, aes(x = X, y = Y, size = layer+1, color = layer+1), shape = 20, stroke = F) +
  scale_size_continuous(name = title_exp, breaks = breaks) +
 # scale_alpha_continuous(name="Nitrogen (tonnes)") +
  scale_color_viridis(name=title_exp, direction = -1, breaks= breaks) +
  guides(colour = guide_legend()) +
  theme_void() +
  coord_sf() +
  theme(legend.position = "left") 

p2
```
```{r}
ggsave(here("figures/Total_nutrients_kg_km2_on_reefs_bubble_plot_ras.png"), dpi = 300, width = 5, height = 5)
```

```{r}
conn_stars<-st_as_stars(conn_ras)
conn_sf<-st_as_sf(conn_stars)
conn_points<-st_centroid(conn_sf) %>% 
  arrange(Connected_nitrogen_on_reefs ) %>% 
  filter(Connected_nitrogen_on_reefs >0)

breaks2<-c(1,10,100,500,900)

p3<-ggplot(data = fiji_basins12) +
  geom_sf(fill = "grey") +
  #geom_sf_text(aes(label = TIKINA), colour = "black") +
  #geom_label_repel(aes(label = TIKINA, geometry = geometry),
  #  stat = "sf_coordinates") +
  geom_sf(data = conn_points, aes(size = Connected_nitrogen_on_reefs, color = Connected_nitrogen_on_reefs)) +
  #geom_point(data = treat_plot_dat2, aes(x = X, y = Y, size = layer+1, color = layer+1), shape = 20, stroke = F) +
  scale_size_continuous(name = title_exp, breaks = breaks2) +
 # scale_alpha_continuous(name="Nitrogen (tonnes)") +
  scale_color_viridis(name=title_exp, direction = -1, breaks = breaks2) +
  guides(colour = guide_legend()) +
  theme_void() +
  theme(legend.position = "left") 
p3
```
```{r}
ggsave(here("figures/Connected_nutrients_kg_km2_on_reefs_bubble_plot_ras.png"), dpi = 300, width = 5, height = 5)
```

```{r}
unconn_stars<-st_as_stars(unconn_ras)
unconn_sf<-st_as_sf(unconn_stars)
unconn_points<-st_centroid(unconn_sf) %>% 
  arrange(Unconnected_nitrogen_on_reefs ) %>% 
  filter(Unconnected_nitrogen_on_reefs >0)

breaks3<-c(1,10,50, 80)

p4<-ggplot(data = fiji_basins12) +
  geom_sf(fill = "grey") +
  #geom_sf_text(aes(label = TIKINA), colour = "black") +
  #geom_label_repel(aes(label = TIKINA, geometry = geometry),
  #  stat = "sf_coordinates") +
  geom_sf(data = unconn_points, aes(size = Unconnected_nitrogen_on_reefs, color = Unconnected_nitrogen_on_reefs)) +
  #geom_point(data = treat_plot_dat2, aes(x = X, y = Y, size = layer+1, color = layer+1), shape = 20, stroke = F) +
  scale_size_continuous(name = title_exp, breaks = breaks3) +
 # scale_alpha_continuous(name="Nitrogen (tonnes)") +
  scale_color_viridis(name=title_exp, direction = -1, breaks = breaks3) +
  guides(colour = guide_legend()) +
  theme_void() +
  coord_sf() +
  theme(legend.position = "left") 
p4
```
```{r}
ggsave(here("figures/Unconnected_nutrients_kg_km2_on_reefs_bubble_plot_ras.png"), dpi = 300, width = 5, height = 5)
```
# Using point polygons - DON"T USE THIS ANYMORE

<!--```{r}
sub_reef_nutri<-treat_plot_dat2 %>%  
  filter(n_reefs>0) %>%  
  mutate(n_reefs_g = n_reefs*1000,
         area_km2 = area_m2*1e-6,
         N_km2 = n_reefs/area_km2,
         N_m2 = n_reefs/area_m2) %>% 
  arrange(N_m2)

# Use fiji_basins to plot basins,
# Use crop_reef_nutri for Tikinas

title_exp <- expression("Nitrogen kg/km"^2)

p<-ggplot(data = fiji_basins12) +
  geom_sf(fill = "grey") +
  geom_point(data = sub_reef_nutri, aes(x = X, y = Y, size = N_km2+1, color = N_km2+1), shape = 20, stroke = F) +
  scale_size_continuous(name=title_exp, trans = "log10") +
  scale_color_viridis(name= title_exp, direction = -1, trans = "log10") +
  guides(colour = guide_legend()) +
  theme_void() +
  coord_sf() +
  theme(legend.position = "left") 
p
```

```{r}
ggsave(here("figures/Nutrients_kg_km2_on_reefs_bubble_plot_log10.png"), dpi = 300)
```

## Connected

```{r}
sub_reef_nutri_treat<-treat_plot_dat2 %>%  
  filter(cnn_n_r>0) %>% 
  mutate(area_km2 = area_m2*1e-6,
         conn_N_km2 = cnn_n_r/area_km2,
         unconn_N_km2 = uncnn__/area_km2) %>% 
  arrange(conn_N_km2)

# Use fiji_basins to plot basins,
# Use crop_reef_nutri for Tikinas

conn_plot<-ggplot(data = fiji_basins12) +
  geom_sf(fill = "grey") +
  #geom_sf_text(aes(label = TIKINA), colour = "black") +
  #geom_label_repel(aes(label = TIKINA, geometry = geometry),
  #  stat = "sf_coordinates") +
  geom_point(data = sub_reef_nutri_treat, aes(x = X, y = Y, size = conn_N_km2+1, color = conn_N_km2+1), shape = 20, stroke = F) +
  scale_size_continuous(name=title_exp, trans = "log10") +
 # scale_alpha_continuous(name="Nitrogen (tonnes)") +
  scale_color_viridis(name=title_exp, direction = -1, trans = "log10") +
  guides(colour = guide_legend()) +
  theme_void() +
  coord_sf() +
  theme(legend.position = "left") 
conn_plot
```

```{r}
ggsave(here("figures/Connected_nutrients_kg_km2_on_reefs_bubble_plot_log10.png"), dpi = 300)
```



## Unconnected

```{r}

unconn_plot<-ggplot(data = fiji_basins12) +
  geom_sf(fill = "grey") +
  #geom_sf_text(aes(label = TIKINA), colour = "black") +
  #geom_label_repel(aes(label = TIKINA, geometry = geometry),
  #  stat = "sf_coordinates") +
  geom_point(data = sub_reef_nutri_treat, aes(x = X, y = Y, size = unconn_N_km2+1, color = unconn_N_km2+1), shape = 20, stroke = F) +
  scale_size_continuous(name=title_exp, trans ="log10") +
 # scale_alpha_continuous(name="Nitrogen (tonnes)") +
  scale_color_viridis(name=title_exp, direction = -1, trans = "log10") +
  guides(colour = guide_legend()) +
  theme_void() +
  coord_sf() +
  theme(legend.position = "left") 

unconn_plot
```

```{r}
ggsave(here("figures/Unconnected_nutrients_kg_km2_on_reefs_bubble_plot_log10.png"), dpi = 300)
```-->








