---
title: "Untitled"
author: "Caitie"
date: '2022-07-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(raster)
library(here)
library(tabularaster)
devtools::install_github("isciences/exactextractr")
library(exactextractr)
library(tmap)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```


# Load data

## Coral reefs


```{r}
reefs<-st_read(here("projected_data/Allen_Coral_Atlas/coral_algae_fiji_crop.shp"))
```

```{r}
#wcmc<-st_read(here("raw_data/UNEP_WCMC_corals/WCMC008_CoralReef2018_Py_v4_1.shp"))

#wcmc2<-st_make_valid(wcmc)

#test<-st_wrap_dateline(wcmc2)

#wcmc_proj<-wcmc2 %>% 
#  st_transform(., t_crs)
```


## Plumes

These currently don't have the wave/current information added, just decay function

```{r}
#plume_files<-list.files(here("output_data/Plumes"), full.names = T)

#r1<-raster(plume_files[1])

#r1p<-projectRaster(r1, crs = t_crs)
#r2p<-projectRaster(r2, crs = t_crs)
#r3p<-projectRaster(r3, crs = t_crs)

#all_rp<-merge(r1p,r2p,r3p)

#merge_rasters(
#  plume_files,
#  output_raster = here("output_data/Plumes/Merged_plumes.tif"),
#  options = character(0),
#  overwrite = FALSE,
#  force_fallback = FALSE
#)

r<-raster(here("output_data/Plumes/Merged_plumes1.tif"))
rp<-projectRaster(r, crs = t_crs)
```

```{r}
#wcmc_buff<-st_buffer(wcmc_proj, byid=TRUE, dist=0)

#wcmc_crop<-st_crop(wcmc_buff, rp) 

#wcmc_crop<-wcmc_crop %>% 
#  mutate(area_m2 = as.numeric(st_area(.)))

#wcmc_crop<-wcmc_crop %>% 
#  dplyr::select(LAYER_NAME, NAME, LOC_DEF)
```
```{r}
cent<-st_centroid(reefs)
```

```{r}
#tm_shape(cent) +
#  tm_dots()
```

# Intersect coral reefs with plumes and calculates the amount of nutrients

```{r}
n_reefs<-exactextractr::exact_extract(rp, reefs, fun = "sum")

n_df<-as.data.frame(n_reefs)

done<-cbind(reefs, n_df)

st_write(done, here("output_data/Nutrients_at_reefs/Nitrogen_on_reefs.shp"), delete_layer = TRUE)
```

```{r}
tmap_mode("view")
tm_shape(done) +
    tm_polygons("n_reefs")
```


