---
title: "Untitled"
author: "Caitie"
date: "23/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(rgdal)
library(raster)
library(gdistance)
library(reshape2)
library(sf)
library(rgrass7)
library(parallel)
library(here)
library(pbmcapply)

source(here("scripts/plume_functions.R"))
```

# Combine all nutrient sources together

Connected

```{r}
conn_N<-raster(here("output_data/Nutrients/Fiji_connected_N_plumes.tif"))
conn_P<-raster(here("output_data/Nutrients/Fiji_connected_P_plumes.tif"))
```

Unconnected

```{r}
septic_N<-raster(here("output_data/Nutrients/Fiji_septic_N_plumes.tif"))
septic_P<-raster(here("output_data/Nutrients/Fiji_septic_P_plumes.tif"))
```

```{r}
direct_N<-raster(here("output_data/Nutrients/Fiji_direct_N_plumes.tif"))
direct_P<-raster(here("output_data/Nutrients/Fiji_direct_P_plumes.tif"))
```

Tourism

```{r}
conn_tourist_N<-raster(here("output_data/Nutrients/Fiji_connected_tourism_N_plumes.tif"))
conn_tourist_P<-raster(here("output_data/Nutrients/Fiji_connected_tourism_P_plumes.tif"))
```

Stack

Change extents so they line up
```{r}
septic_N <- extend(septic_N,direct_N)
conn_N<-extend(conn_N, septic_N)
septic_P <- extend(septic_P,direct_N)
conn_P<-extend(conn_P, septic_N)
direct_N <- extend(direct_N,septic_N)
direct_P <- extend(direct_P,septic_N)
conn_tourist_N<-extend(conn_tourist_N, septic_N)
conn_tourist_P<-extend(conn_tourist_P, septic_N)
```



```{r}
all<-stack(conn_N, conn_P, septic_N, septic_P, direct_N, direct_P,conn_tourist_N, conn_tourist_P)
```


# Calculate the amount of nutrients reaching coral reefs

Coral reef layer

```{r}
#corals<-st_read(here("raw_data/Coral_reefs/Fiji_selected_corals.shp"))
#corals<-st_read("/home/kuempel/Cumulative_threats_data/reefs/EEZ_Coral.shp")
corals<-st_read("/home/kuempel/Cumulative_threats_data/reefs/WCMC008_CoralReef2018_Py_v4.shp")

fji_corals<-corals %>% 
  filter(PARENT_ISO == "FJI")
fji_corals<-st_transform(fji_corals, crs(all))

fji_corals<-st_cast(st_as_sf(fji_corals),"POLYGON")

fji_corals<-fji_corals %>% 
  mutate(ID = 1:nrow(fji_corals))

corals_list<-split(fji_corals, fji_corals$ID)

#corals_list<-corals_list[901:910]

```

```{r}
nutri_corals<-pbmclapply(corals_list, coral_func, mc.cores = 20, mc.style = "ETA")

corals_processed<-do.call(rbind,nutri_corals[1:length(nutri_corals)])



corals_processed<-corals_processed %>% 
  mutate(Fiji_connected_N_plumes=replace_na(Fiji_connected_N_plumes, 0),
         Fiji_connected_P_plumes=replace_na(Fiji_connected_P_plumes, 0),
         Fiji_septic_N_plumes=replace_na(Fiji_septic_N_plumes,0),
         Fiji_septic_P_plumes=replace_na(Fiji_septic_P_plumes,0),
         Fiji_direct_N_plumes=replace_na(Fiji_direct_N_plumes,0),
         Fiji_direct_P_plumes=replace_na(Fiji_direct_P_plumes,0),
         Fiji_connected_tourism_N_plumes=replace_na(Fiji_connected_tourism_N_plumes,0),
         Fiji_connected_tourism_P_plumes=replace_na(Fiji_connected_tourism_P_plumes,0),
         Total_N =Fiji_connected_N_plumes+Fiji_septic_N_plumes+Fiji_direct_N_plumes+Fiji_connected_tourism_N_plumes,
         Total_P =Fiji_connected_P_plumes+Fiji_septic_P_plumes+Fiji_direct_P_plumes+Fiji_connected_tourism_P_plumes,
         Total_nutrients = Total_N + Total_P) %>% 
  rename(conn_N = Fiji_connected_N_plumes,
         conn_P = Fiji_connected_P_plumes,
         direct_N = Fiji_direct_N_plumes,
         direct_P = Fiji_direct_P_plumes,
         septic_N = Fiji_septic_N_plumes,
         septic_P = Fiji_septic_P_plumes,
         tourist_N = Fiji_connected_tourism_N_plumes,
         tourist_P = Fiji_connected_tourism_P_plumes)
```

```{r}
st_write(corals_processed, here("output_data/Nutrients/Fiji_corals_nutrient_export.shp"), append = F)
```


