---
title: "Untitled"
author: "Caitie"
date: "16/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(sf)
library(here)
library(raster)
library(ggplot2)
library(rgdal)
library(gdistance)
library(reshape2)
library(rgrass7)
library(parallel)
library(tmap)
remotes::install_github("SEEG-Oxford/seegSDM")
library(seegSDM)

```

# Nutrients at each pourpoint

```{r}
stp_crs<-st_read(here("output_data/Sewage_plants/Nutrients_at_STP.shp"))

stp<-stp_crs %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry)
```

# Location of pourpoints

```{r}
stp_pp<-st_read("/home/kuempel/Waste_water_data/Fiji/Sewage_plants/All_STP_outfalls_Fiji.shp") %>% 
    mutate(ID = ifelse(Name == "Pacific Harbor Sewage Outfall", 2,
                            ifelse(Name == "PWD (Kinoya) Sewage Outfall" , 3,
                                 #  ifelse(Name == "Naboro", 4,
                                   #       ifelse(Name == "Nadali", 5,
                                                 ifelse(Name ==  "Labasa Outfall", 6,
                                                        ifelse(Name == "Lautoka Natabua Sewage Outfall", 7,
                                                               ifelse(Name ==  "Nadi outfall" , 8,
                                                                      ifelse(Name == "Sigatoka Outfall", 9,
                                                                             ifelse(Name == "Ba outfall", 10, NA))))))))

stp_pp_proj<-st_transform(stp_pp, st_crs(stp_crs)) 

# Need to look into outfalls again
```

Join pourpoints to nutrients

```{r}
pour_points<-full_join(stp_pp_proj, stp, by = "ID") %>% 
  dplyr::select(Name, STP, ID, N, P)
```


# Diffusion model

Plume function

```{r}
sed_flow_N<-function(pp_sf,#list of pour points
                   ocean_raster,
                   buffer_value,#buffer from pour point
                   resolution_raster,#in meters
                   searchdistance #max searching distance to snap the points to the coast
                   
){
  #set initial sediment value
  initial.value<-pp_sf@data$N
  #create buffer around point and clip ocean raster
  point<-st_as_sf(pp_sf,coords=c("longitude.y","latitude.y"))#first need to convert to sf object
  point_buff<-st_buffer(point, buffer_value)#
  r1<-crop(ocean_raster,extent(point_buff),snap = "near")
  
  #create raster to match point location to ocean raster
  #for a new version we can use the function nearest.raster.point, but I had already solved this issue 
  #rasterizing the point
  
  point_1000<-st_buffer(point, 500)#
  #create raster of pour point
  r2  <- raster(ncol=1, nrow=1, xmn=extent(point_1000)[1], xmx=extent(point_1000)[2], ymn=extent(point_1000)[3], ymx=extent(point_1000)[4])
  crs(r2)<-crs(ocean_raster)
  r2[]<-initial.value
  
  #now sum to match rasters of different extent
  
  extend_all =
    function(rasters){
      extent(Reduce(extend,rasters))
    }
  
  sum_all =
    function(rasters, extent){
      re = lapply(rasters, function(r){extend(r,extent)})
      Reduce("+", re)
    }
  
  rasterOptions(tolerance = 1)
  r3 = sum_all(list(r1,r2), extend_all(list(r1,r2)))
  
  #identify if points are on the coast
  
  if(length(which(r3[]>0))< 1){
    snap_point<-nearestLand(coordinates(r2)[],r1,searchdistance)
    pp_sf@coords<-snap_point
    point<-st_as_sf(pp_sf,coords=c("longitude.y","latitude.y"))
    point_1000<-st_buffer(point, 500)#
    #create raster of pour point
    r2  <- raster(ncol=1, nrow=1, xmn=extent(point_1000)[1], xmx=extent(point_1000)[2], ymn=extent(point_1000)[3], ymx=extent(point_1000)[4])
    crs(r2)<-crs(ocean_raster)
    r2[]<-initial.value
    r3 = sum_all(list(r1,r2), extend_all(list(r1,r2)))
  }
  
  #find exact pour point position
  pour_point <- which(r3[] >0)
  
  fromCoords<-pp_sf@coords
  
  raster_temp<-r3
  r<-raster_temp
  
  #create transition layer to be used in cost layer
  transition_layer<-transition(r1,transitionFunction=mean, directions=8)
  
  transition_layer<-geoCorrection(transition_layer,scl=FALSE)
  
  cost_layer<-accCost(transition_layer, fromCoords)
  #calculate distance frequencies
  
  
  initial.value<-pp_sf@data$N
  
  values<-rasterToPoints(cost_layer)[,3]
  frequency_distances<-as.data.frame(table(round(values,1)))
  frequency_distances<-subset(frequency_distances,frequency_distances[1] != Inf)
  frequency_distances[,1]<-as.character(frequency_distances[,1])
  frequency_distances[,1]<-as.numeric(frequency_distances[,1])
  new.values<-initial.value
  raster_temp[pour_point]<-initial.value*0.005  ##Decay parameter
  
  for(i in 2:nrow(frequency_distances))
  {
    cellstoreplace<-which(round(cost_layer[],1)==frequency_distances[i,1])
    percell = initial.value * 0.005  ## decay parameter
    sumcells = percell * length(cellstoreplace)
    remain = initial.value - sumcells
    initial.value = remain
    raster_temp[cellstoreplace]<-percell
    if(remain < pp_sf@data$N*0.0005) {
      break
    }
  }
  raster_temp[which(raster_temp[]==0)]<-NA
  if(length(unique(raster_temp[]))>1){
    raster_temp<-trim(raster_temp)
  }
  return(raster_temp)
}
```

```{r}
sed_flow_P<-function(pp_sf,#list of pour points
                   ocean_raster,
                   buffer_value,#buffer from pour point
                   resolution_raster,#in meters
                   searchdistance #max searching distance to snap the points to the coast
                   
){
  #set initial sediment value
  initial.value<-pp_sf@data$N
  #create buffer around point and clip ocean raster
  point<-st_as_sf(pp_sf,coords=c("longitude.y","latitude.y"))#first need to convert to sf object
  point_buff<-st_buffer(point, buffer_value)#
  r1<-crop(ocean_raster,extent(point_buff),snap = "near")
  
  #create raster to match point location to ocean raster
  #for a new version we can use the function nearest.raster.point, but I had already solved this issue 
  #rasterizing the point
  
  point_1000<-st_buffer(point, 500)#
  #create raster of pour point
  r2  <- raster(ncol=1, nrow=1, xmn=extent(point_1000)[1], xmx=extent(point_1000)[2], ymn=extent(point_1000)[3], ymx=extent(point_1000)[4])
  crs(r2)<-crs(ocean_raster)
  r2[]<-initial.value
  
  #now sum to match rasters of different extent
  
  extend_all =
    function(rasters){
      extent(Reduce(extend,rasters))
    }
  
  sum_all =
    function(rasters, extent){
      re = lapply(rasters, function(r){extend(r,extent)})
      Reduce("+", re)
    }
  
  rasterOptions(tolerance = 1)
  r3 = sum_all(list(r1,r2), extend_all(list(r1,r2)))
  
  #identify if points are on the coast
  
  if(length(which(r3[]>0))< 1){
    snap_point<-nearestLand(coordinates(r2)[],r1,searchdistance)
    pp_sf@coords<-snap_point
    point<-st_as_sf(pp_sf,coords=c("longitude.y","latitude.y"))
    point_1000<-st_buffer(point, 500)#
    #create raster of pour point
    r2  <- raster(ncol=1, nrow=1, xmn=extent(point_1000)[1], xmx=extent(point_1000)[2], ymn=extent(point_1000)[3], ymx=extent(point_1000)[4])
    crs(r2)<-crs(ocean_raster)
    r2[]<-initial.value
    r3 = sum_all(list(r1,r2), extend_all(list(r1,r2)))
  }
  
  #find exact pour point position
  pour_point <- which(r3[] >0)
  
  fromCoords<-pp_sf@coords
  
  raster_temp<-r3
  r<-raster_temp
  
  #create transition layer to be used in cost layer
  transition_layer<-transition(r1,transitionFunction=mean, directions=8)
  
  transition_layer<-geoCorrection(transition_layer,scl=FALSE)
  
  cost_layer<-accCost(transition_layer, fromCoords)
  #calculate distance frequencies
  
  
  initial.value<-pp_sf@data$N
  
  values<-rasterToPoints(cost_layer)[,3]
  frequency_distances<-as.data.frame(table(round(values,1)))
  frequency_distances<-subset(frequency_distances,frequency_distances[1] != Inf)
  frequency_distances[,1]<-as.character(frequency_distances[,1])
  frequency_distances[,1]<-as.numeric(frequency_distances[,1])
  new.values<-initial.value
  raster_temp[pour_point]<-initial.value*0.005  ##Decay parameter
  
  for(i in 2:nrow(frequency_distances))
  {
    cellstoreplace<-which(round(cost_layer[],1)==frequency_distances[i,1])
    percell = initial.value * 0.005  ## decay parameter
    sumcells = percell * length(cellstoreplace)
    remain = initial.value - sumcells
    initial.value = remain
    raster_temp[cellstoreplace]<-percell
    if(remain < pp_sf@data$N*0.0005) {
      break
    }
  }
  raster_temp[which(raster_temp[]==0)]<-NA
  if(length(unique(raster_temp[]))>1){
    raster_temp<-trim(raster_temp)
  }
  return(raster_temp)
}
```

Apply function to points list

```{r}
#ocean_raster<-raster(here("raw_data/Global/oceans_moll.tif"))

#ocean_raster<-projectRaster(ocean_raster, crs = as.character(crs(stp_pp_proj)))

#writeRaster(ocean_raster, here("projected_data/oceans_moll_proj.tif"))

ocean_raster<-raster(here("projected_data/oceans_moll_proj.tif"))
```


```{r}
pour_points<-pour_points %>% 
  filter(!is.na(ID) == T,
         !STP == "Rewa Outfall",
         !is.na(Name) == T) 

p_extent=st_as_sfc(st_bbox(pour_points))
p_extent_sub = st_make_grid(p_extent,n = c(40,20)) %>%
               st_as_sf() %>% 
               rename(geom=x) %>%
               mutate(group=1:nrow(.))
tm_shape(p_extent_sub)+tm_polygons()
pour_points = st_join(pour_points, p_extent_sub, join = st_intersects) %>% 
              mutate(ID=1:nrow(.)) %>% 
  as_Spatial

  point_list<-split(pour_points,as.character(pour_points@data$ID))
  re = mclapply(point_list, sed_flow_N, ocean_raster, 80000, c(1110,894), 90000, mc.cores = 1)
  
  # Set extent for all outputs to the max extent needed, e.g., newextent
  newextent<-extent(Reduce(extend,re)) # Get max extent of all objects
  re_ext=mclapply(re, extend, newextent, mc.cores=1) # Use fewer cores as this gets more memory heavy
  gc()
  
  # Reclass NAs to 0
  re_ext = mclapply(re_ext, mc.cores = 1, function(x) reclassify(x, cbind(NA,0))) # Reclass NA to 0, in a more memory friendly way,apparently...
  gc()

  # Add all rasters in the group together + mask out land areas is desired
  sed_plume_merge = Reduce("+", re_ext) 
  sed_plume_merge = sed_plume_merge * ocean_raster # mask out land; disregard the warning

  writeRaster(sed_plume_merge, here(paste0("output_data/Nutrients/sed_plume_group_", i,".tif")), overwrite = TRUE, options=c("compress=deflate","tiled=yes","num_threads=6")) 

  print(paste0("Group ", i," of ", length(unique(pour_points$group)), " groups is completed."))
  rm(list = c('sed_plume_merge', 're', 're_ext', 'newextent', 'point_list'))
  gc()

  # Add all rasters in the group together + mask out land areas is desired
  sed_plume_merge = Reduce("+", re_ext) 
  sed_plume_merge = sed_plume_merge * ocean_raster # mask out land; disregard the warning

  writeRaster(sed_plume_merge, here("output_data/Nutrients/Fiji_nutrient_plumes.tif"), overwrite = TRUE, options=c("compress=deflate","tiled=yes","num_threads=6"))

```
