---
title: "Untitled"
author: "Caitie"
date: "16/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(raster)
library(here)
library(sf)
```

```{r}
nutri_results<-read.csv(here("output_data/Results/Nutrient_results.csv"))

```

# Residential

```{r}
residential_N<-nutri_results %>% 
  filter(Type %in% c("Connected", "Septic", "Direct", "Coastal_septic", "Coastal_direct"),
         Nutrient == "N") 
```

```{r}
residential_P<-nutri_results %>% 
  filter(Type %in% c("Connected", "Septic", "Direct", "Coastal_septic", "Coastal_direct"),
         Nutrient == "P") 
```

## Total excreted

```{r}
n_excrete<-sum(residential_N$Excreted, na.rm = T)
p_excrete<-sum(residential_P$Excreted, na.rm = T)

n_excrete
p_excrete

```

## Total effluent

```{r}
n_effluent<-sum(residential_N$Effluent, na.rm = T)
p_effluent<-sum(residential_P$Effluent, na.rm = T)

n_effluent
p_effluent
```

## Connected

```{r}
conn_N_eff <- residential_N %>% 
  filter(Type == "Connected")%>% 
  dplyr::select("Effluent") %>% 
  unique()

conn_P_eff <- residential_P %>% 
  filter(Type == "Connected") %>% 
  dplyr::select("Effluent") %>% 
  unique()

```

Percent of effluent that is from WWTP

```{r}
conn_N_eff/n_effluent
conn_P_eff/p_effluent
```

```{r}
conn_N_ex <- residential_N %>% 
  filter(Type == "Connected")%>% 
  dplyr::select("Excreted") %>% 
  unique()

conn_P_ex <- residential_P %>% 
  filter(Type == "Connected") %>% 
  dplyr::select("Excreted") %>% 
  unique

conn_N_ex
conn_P_ex
```

```{r}
conn_N_eff
conn_P_eff
```

```{r}
conn_N_eff/conn_N_ex
conn_P_eff/conn_P_ex
```
Correlation/validation with WWTP values


```{r}
wwtp_compare<-read.csv(here("output_data/Sensitivity/WWTP_compare_nutrients.csv"))

```


```{r}
cor.test(wwtp_compare$N_final*0.001, wwtp_compare$N_eff_actual, method = "pearson")
cor.test(wwtp_compare$P_final*0.001, wwtp_compare$P_eff_actual, method = "pearson")
```

## Septic

```{r}
septic_N_ex <- residential_N %>% 
  filter(Type == "Septic")%>% 
  dplyr::select("Excreted") %>% 
  unique()

septic_P_ex <- residential_P %>% 
  filter(Type == "Septic") %>% 
  dplyr::select("Excreted") %>% 
  unique()

```

```{r}
septic_N_eff <- residential_N %>% 
  filter(Type == "Septic")%>% 
  dplyr::select("Effluent") %>% 
  unique()

septic_P_eff <- residential_P %>% 
  filter(Type == "Septic") %>% 
  dplyr::select("Effluent") %>% 
  unique()

coastal_septic_N_eff <- residential_N %>% 
  filter(Type == "Coastal_septic")%>% 
  dplyr::select("Effluent") %>% 
  unique()

coastal_septic_P_eff <- residential_P %>% 
  filter(Type == "Coastal_septic") %>% 
  dplyr::select("Effluent") %>% 
  unique()

```

## Direct

```{r}
direct_N_ex <- residential_N %>% 
  filter(Type == "Direct")%>% 
  dplyr::select("Excreted") %>% 
  unique()

direct_P_ex <- residential_P %>% 
  filter(Type == "Direct") %>% 
  dplyr::select("Excreted") %>% 
  unique()

```

```{r}
direct_N_eff <- residential_N %>% 
  filter(Type == "Direct")%>% 
  dplyr::select("Effluent") %>% 
  unique()

direct_P_eff <- residential_P %>% 
  filter(Type == "Direct") %>% 
  dplyr::select("Effluent") %>% 
  unique()

coastal_direct_N_eff <- residential_N %>% 
  filter(Type == "Coastal_direct")%>% 
  dplyr::select("Effluent") %>% 
  unique()

coastal_direct_P_eff <- residential_P %>% 
  filter(Type == "Coastal_direct") %>% 
  dplyr::select("Effluent") %>% 
  unique()

```

Total excreted

```{r}
septic_N_ex
septic_P_ex
```

```{r}
(septic_N_eff + coastal_septic_N_eff)/septic_N_ex

septic_N_eff + coastal_septic_N_eff
```
```{r}
(septic_P_eff + coastal_septic_P_eff)/septic_P_ex

septic_P_eff + coastal_septic_P_eff
```

```{r}
direct_N_ex
direct_P_ex
```



```{r}
(direct_N_eff + coastal_direct_N_eff)/direct_N_ex

direct_N_eff + coastal_direct_N_eff
```

```{r}
(direct_P_eff + coastal_direct_P_eff)/direct_P_ex

direct_P_eff + coastal_direct_P_eff
```

```{r}
coastal_septic_N_eff/(septic_N_eff + coastal_septic_N_eff)
coastal_direct_N_eff/(direct_N_eff + coastal_direct_N_eff)
```

