---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(leaflet)
library(shiny)
library(tmap)
library(here)
library(sf)
library(tidyverse)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

# Fiji basins/Fiji outline

```{r}
fiji_basins12<-st_read(here("projected_data/Basins/Fiji_basins12.shp")) %>% 
  filter(!MAIN_BAS %in% c(5120082250)) 

fiji_basins<-st_transform(fiji_basins12, t_crs)
```

# Population serviced by each treatment type per watershed

Percent of population that is septic vs direct in each watershed and bubbles on STP with population serviced

```{r}
septic<-raster(here("output_data/Population/Septic_population.tif"))
direct<-raster(here("output_data/Population/Direct_population.tif"))

pop_treat_basins<-fiji_basins %>% 
  dplyr::select(HYBAS_ID, MAIN_BAS) %>% 
  mutate(sep_pop = extract(septic, fiji_basins, fun = sum, na.rm = T),
         dir_pop = extract(direct, fiji_basins, fun = sum, na.rm = T))

pop_treat_basins2<-pop_treat_basins %>% 
  mutate(sep_pop = as.numeric(sep_pop),
         sep_pop = ifelse(is.na(sep_pop) == T, 0, as.numeric(sep_pop)),
         dir_pop = as.numeric(dir_pop),
         dir_pop = ifelse(is.na(dir_pop) == T, 0, as.numeric(dir_pop)),
         total_pop = sep_pop + dir_pop,
         perc_sep = sep_pop/total_pop)

  
```


```{r}
septic_pop<-tm_shape(pop_treat_basins2) +
    tm_polygons("sep_pop", 
                style = "cont", 
                title = "Population") +
  tm_layout(title = "Septic")

septic_pop
```
```{r}
direct_pop<-tm_shape(pop_treat_basins2) +
    tm_polygons("dir_pop", 
                style = "cont", 
                title = "Population") +
  tm_layout(title = "Direct")

direct_pop
```

```{r}
#WWTP pourpoint locations
stp_pp<-st_read(here("output_data/Sewage_plants/All_STP_outfalls_Fiji.shp")) %>% 
  st_transform(., crs = t_crs) %>% 
    mutate(ID = ifelse(Name == "Pacific Harbor Sewage Outfall", 1,
                            ifelse(Name == "PWD (Kinoya) Sewage Outfall" , 2,
                                   ifelse(Name == "Naboro", NA,
                                          ifelse(Name == "Nadali", 3,
                                                 ifelse(Name ==  "Labasa Outfall", 4,
                                                        ifelse(Name == "Lautoka Natabua Sewage Outfall", 5,
                                                               ifelse(Name ==  "Nadi outfall" , 6,
                                                                      ifelse(Name == "Sigatoka Outfall", 7,
                                                                             ifelse(Name == "Ba outfall", 8, NA))))))))))

stp_pp_proj<-st_transform(stp_pp, crs = t_crs) %>% 
  mutate(ID = ifelse(Name == "Rewa Outfall", 3, 
                     ifelse(Name == "ACS Outfall",NA,
                            ifelse(Name == "Naboro Outfall", NA,
                                   ifelse(Name == "Wailada Outfall", NA, as.numeric(ID)))))) %>% 
  filter(!is.na(ID) == T)
#WWTP people serviced
```


```{r}
stp_pop<-read.csv(here("output_data/Sewage_plants/STP_population_check.csv")) %>% 
  mutate(ID = ifelse(STP == "Deuba WWTP", 1,
                     ifelse(STP == "Kinoya WWTP", 2,
                            ifelse(STP == "Nadali WWTP", 3,
                                   ifelse(STP == "Namara TP", 4,
                                          ifelse(STP == "Natabua WWTP", 5,
                                                 ifelse(STP == "Navakai WWTP", 6,
                                                        ifelse(STP == "Olosara", 7, 8))))))),
         label = ifelse(STP == "Deuba WWTP", "Pacific Harbor",
                     ifelse(STP == "Kinoya WWTP", "Kinoya",
                            ifelse(STP == "Nadali WWTP", "Rewa",
                                   ifelse(STP == "Namara TP", "Labasa",
                                          ifelse(STP == "Natabua WWTP", "Lautoka",
                                                 ifelse(STP == "Navakai WWTP", "Nadi",
                                                        ifelse(STP == "Olosara", "Sigatoka", "Ba"))))))))
```

```{r}
connected_pop<-full_join(stp_pp_proj, stp_pop, by = "ID") %>% 
  filter(!is.na(STP) == T)

basins_diss<-fiji_basins %>% 
  mutate(ID = as.numeric(1)) %>% 
  group_by(ID) %>% 
  summarise(area_km2 = sum(area_km2, na.rm = T))
```

```{r}

connected_pop_plot<-tm_shape(basins_diss) +
  tm_borders() +
  tm_shape(connected_pop)+
  tm_bubbles(col = "estimated",
             style = "cont",
             size = 0.5,
             border.col = "black", 
             border.lwd = 2, 
             title.shape = "Population", 
             title.col = "Population") +
  tm_layout(title = "Connected") #+
  #tm_text("label", size = 1, auto.placement = 1.5, col = "darkblue")

connected_pop_plot

```

```{r}
pop_final<-tmap_arrange(direct_pop, septic_pop, connected_pop_plot, nrow = 1)

pop_final
```

```{r}
tmap_save(pop_final, here("figures/Treatment_population_map.png"), dpi = 300, width = 10, height = 5)
```

















```{r}
r<-raster(here("output_data/Nutrients/Fiji_connected_N_plumes.tif"))
pal<-colorNumeric(c("#0C2C84", "#ff7400", "#ff0000"), values(r),
  na.color = "transparent")

leaflet() %>% addTiles() %>% 
  addRasterImage(r, colors = pal, opacity = 0.8) %>% 
  addLegend(pal = pal, values = values(r),
            title= "Connected Nitrogen pollution")
```
```{r}
r<-raster(here("output_data/Nutrients/Fiji_connected_P_plumes.tif"))
pal<-colorNumeric(c("#0C2C84", "#ff7400", "#ff0000"), values(r),
  na.color = "transparent")

leaflet() %>% addTiles() %>% 
  addRasterImage(r, colors = pal, opacity = 0.8) %>% 
  addLegend(pal = pal, values = values(r),
            title= "Connected Nitrogen pollution")
```

```{r}
r<-raster(here("output_data/Nutrients/Fiji_septic_N_plumes.tif"))
pal<-colorNumeric(c("#0C2C84", "#ff7400", "#ff0000"), values(r),
  na.color = "transparent")

leaflet() %>% addTiles() %>% 
  addRasterImage(r, colors = pal, opacity = 0.8) %>% 
  addLegend(pal = pal, values = values(r),
            title= "Unonnected Nitrogen pollution")
```


```{r}
r<-raster(here("output_data/Nutrients/Fiji_septic_P_plumes.tif"))
pal<-colorNumeric(c("#0C2C84", "#ff7400", "#ff0000"), values(r),
  na.color = "transparent")

leaflet() %>% addTiles() %>% 
  addRasterImage(r, colors = pal, opacity = 0.8) %>% 
  addLegend(pal = pal, values = values(r),
            title= "Unonnected Phosphorous pollution")
```

```{r}
r<-raster(here("output_data/Nutrients/Fiji_direct_N_plumes.tif"))
pal<-colorNumeric(c("#0C2C84", "#ff7400", "#ff0000"), values(r),
  na.color = "transparent")

leaflet() %>% addTiles() %>% 
  addRasterImage(r, colors = pal, opacity = 0.8) %>% 
  addLegend(pal = pal, values = values(r),
            title= "Connected tourist nitrogen pollution")
```

```{r}
r<-raster(here("output_data/Nutrients/Fiji_direct_P_plumes.tif"))
pal<-colorNumeric(c("#0C2C84", "#ff7400", "#ff0000"), values(r),
  na.color = "transparent")

leaflet() %>% addTiles() %>% 
  addRasterImage(r, colors = pal, opacity = 0.8) %>% 
  addLegend(pal = pal, values = values(r),
            title= "Connected tourist phosphorous pollution")
```

# Data for mapping
```{r}
fiji_basins12<-st_read(here("projected_data/Basins/Fiji_basins12.shp")) %>% 
  filter(!MAIN_BAS %in% c(5120082250)) %>% 
  mutate(ID = as.numeric(1)) %>% 
  group_by(ID) %>% 
  summarise(area_km2 = sum(area_km2, na.rm = T))


coral_export<-st_read(here("output_data/Nutrients/Fiji_corals_nutrient_export.shp")) 

coral_export<- coral_export %>% 
  st_transform(., st_crs(fiji_basins12)) %>%
  st_make_valid() %>% 
  st_crop(., fiji_basins12) %>% 
  mutate(N_tonnes=Total_N *0.001,
         P_tonnes= Total_P *0.001)

#coral_export_long<-coral_export %>% 
#  pivot_longer(., cols =c("Fj_c_N_" ,"Fj_c_P_" , "Fj_n_N_" , "Fj_n_P_" , "Fj___N_" , "Fj___P_" , "Total_N" , "Total_P" , "Ttl_ntr"), #names_to = "type", values_to = "value") %>% 
#  st_as_sf()

#conn_N<-raster(here("output_data/Nutrients/Fiji_connected_N_plumes.tif"))
```
```{r}
fiji<-tm_shape(fiji_basins12) +
  tm_borders() 

fiji
```


```{r}
test<-coral_export %>% 
  mutate(Ttl_ntr=ifelse(Ttl_ntr<=0, NA, as.numeric(Ttl_ntr)))

total_nutrients<-tm_shape(test) +
  tm_fill(col = "Ttl_ntr", 
          title = "Total nutrients (kg)", 
          style = "order",
          textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "top"))

total_nutrients
```

```{r}
test<-coral_export %>% 
  mutate(Total_N=ifelse(Total_N<=0, NA, as.numeric(Total_N)))

total_N<-tm_shape(test) +
  tm_fill(col = "Total_N", 
          title = "Nitrogen (kg)", 
          style = "order",
           textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "top"))
```


```{r}
test<-coral_export %>% 
  mutate(Total_P=ifelse(Total_P<=0, NA, as.numeric(Total_P)))

total_P<-tm_shape(test) +
  tm_fill(col = "Total_P", 
          title = "Phosphorus (kg)", 
          style = "order",
           textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "top"))
```

```{r}
nutri1<-fiji + total_N +tm_scale_bar(position=c("right", "bottom"))
nutri2<-fiji + total_P
nutri3<-fiji + total_nutrients
```


```{r}
n_p_all<-tmap_arrange(nutri1, nutri2, nutri3, ncol = 3, nrow = 1)
n_p_all
```

```{r}
tmap_save(n_p_all, here("figures/Fiji_N_P_all.png"), width=20, height=8, asp=0)
```

```{r}
test<-coral_export %>% 
    mutate(conn_N=ifelse(conn_N<=0, NA, as.numeric(conn_N)))

conn_N<-tm_shape(test) +
  tm_fill(col = "conn_N", 
          title = "Nitrogen (kg)", 
          style = "order",
          textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "bottom"))

#conn_N
```

```{r}
test<-coral_export %>% 
    mutate(septc_N=ifelse(septc_N<=0, NA, as.numeric(septc_N)))

septic_N<-tm_shape(test) +
  tm_fill(col = "septc_N", 
          title = "Nitrogen (kg)", 
          style = "order",
          textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "bottom"))
```

```{r}
test<-coral_export %>% 
    mutate(dirct_N=ifelse(dirct_N<=0, NA, as.numeric(dirct_N)))

direct_N<-tm_shape(test) +
  tm_fill(col = "dirct_N", 
          title = "Nitrogen (kg)", 
          style = "order",
          textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "bottom"))
```
 
```{r}
test<-coral_export %>% 
    mutate(torst_N=ifelse(torst_N<=0, NA, as.numeric(torst_N)))

tourism_N<-tm_shape(test) +
  tm_fill(col = "torst_N", 
          title = "Nitrogen (kg)", 
          style = "order",
          textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "bottom"))
```

```{r}
n1<-fiji + conn_N +tm_scale_bar(position=c("right", "bottom")) + tm_layout(title = "Connected populations")
n2<-fiji + septic_N + tm_layout(title = "Septic populations")
n3<-fiji + direct_N + tm_layout(title = "Direct populations")
n4<-fiji + tourism_N + tm_layout(title = "Connected tourism")
```


```{r}
nitrogen<-tmap_arrange(n1, n2, n3, n4, ncol = 2, nrow = 2)
nitrogen
```

```{r}
tmap_save(nitrogen, here("figures/Fiji_nitrogen.png"), width=10, height=10, asp=0)
```


```{r}
test<-coral_export %>% 
    mutate(conn_P=ifelse(conn_P<=0, NA, as.numeric(conn_P)))

conn_P<-tm_shape(test) +
  tm_fill(col = "conn_P", 
          title = "Phosphorus (kg)", 
          style = "order",
          textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "bottom"))

#conn_P
```

```{r}
test<-coral_export %>% 
    mutate(septc_P=ifelse(septc_P<=0, NA, as.numeric(septc_P)))

septic_P<-tm_shape(test) +
  tm_fill(col = "septc_P", 
          title = "Phosphorus (kg)", 
          style = "order",
          textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "bottom"))
```

```{r}
test<-coral_export %>% 
    mutate(dirct_P=ifelse(dirct_P<=0, NA, as.numeric(dirct_P)))

direct_P<-tm_shape(test) +
  tm_fill(col = "dirct_P", 
          title = "Phosphorus (kg)", 
          style = "order",
          textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "bottom"))
```
 
```{r}
test<-coral_export %>% 
    mutate(torst_P=ifelse(torst_P<=0, NA, as.numeric(torst_P)))

tourism_P<-tm_shape(test) +
  tm_fill(col = "torst_P", 
          title = "Phosphorus (kg)", 
          style = "order",
          textNA = "Zero or NA") +
  tm_layout(legend.outside = FALSE, bg.color = "lightblue",
            legend.position=c("left", "bottom"))
```



```{r}
p1<-fiji + conn_P +tm_scale_bar(position=c("right", "bottom")) + tm_layout(title = "Connected populations")
p2<-fiji + septic_P + tm_layout(title = "Septic populations")
p3<-fiji + direct_P + tm_layout(title = "Direct populations")
p4<-fiji + tourism_P+ tm_layout(title = "Connected tourism")
```


```{r}
phosphorus<-tmap_arrange(p1, p2, p3,p4, ncol = 2, nrow = 2)
phosphorus
```


```{r}
tmap_save(phosphorus, here("figures/Fiji_phosphorus.png"), width=10, height=10, asp=0)
```