---
title: "Untitled"
author: "Caitie"
date: "17/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(sf)
library(here)
library(raster)
library(ggplot2)
library(rgdal)
library(gdistance)
library(reshape2)
library(rgrass7)
library(parallel)
library(tmap)
#remotes::install_github("SEEG-Oxford/seegSDM")
library(seegSDM)
library(tabularaster)
library(units)
library(lwgeom)
```


# Rivers

```{r}
rivers<-st_read(here("projected_data/Rivers/Fiji_rivers.shp"))
```


# Basins

```{r}
# Read in data and calculate area
#test<-st_read("/home/kuempel/Waste_water_data/Fiji/Basins/BasinATLAS_v10_shp/BasinATLAS_v10_lev12.shp")
#basins12<-st_read("/home/kuempel/Waste_water_data/Fiji/Basins/BasinATLAS_v10_shp/BasinATLAS_v10_lev12.shp")
basins12<-st_read(here("raw_data/Basins/BasinATLAS_v10_lev12.shp"))

basins12_proj<-st_transform(basins12, st_crs(rivers))

rivers_proj<-st_transform(rivers, st_crs(basins12))
#basins_crop<-st_crop(basins12_proj, extent(rivers))
#test<- basins12_proj %>% 
#  filter(MAIN_BAS %IN%)

#test<-st_make_valid(basins12_proj)


#fiji_basins12<-st_read(here("projected_data/Basins/Fiji_basins12.shp")) 

#fiji_basins_df<-fiji_basins12 %>% 
#  as.data.frame() %>% 
#  dplyr::select(HYBAS_ID, NEXT_DOWN,area_km2, -ID)

```

# Pourpoints
Method from here: https://stackoverflow.com/questions/55106950/r-sf-intersect-lines-with-the-borders-of-multipolygons-extract-coordinates-of

Here is the new method I should use: https://gis.stackexchange.com/questions/251101/return-end-vertices-of-an-sf-linestring

```{r}
# Read in data
sub_fiji_rivers<- rivers_proj %>% 
  filter(NEXT_DOWN == 0) %>% 
  st_cast(., "LINESTRING")


#If you only want the endpoints, then st_line_sample is what you are looking for:

pnts<-st_endpoint(sub_fiji_rivers) 

pnts_xy<-st_coordinates(pnts) 

data_per_river<-st_join(sub_fiji_rivers,basins12)
data_per_river<-data_per_river[!duplicated(data_per_river$HYRIV_ID),]

data_per_river<-st_transform(data_per_river, st_crs(rivers)) %>% 
  rename(riv_dis = dis_m3_pyr.x,
         bas_dis = dis_m3_pyr.y)

pnts<-st_transform(pnts, st_crs(rivers))

pb <- txtProgressBar(min = 0, max = nrow(data_per_river), style = 3) 
pour_points<-list()
for (i in 1:nrow(data_per_river)){
  setTxtProgressBar(pb, i)
  points_line<- st_cast(data_per_river[i,], "POINT")
  pour_points[[i]]<- points_line[nrow(points_line),]
  data_per_river[i,"pp_x"]<-extent(pour_points[[i]])[1]
  data_per_river[i,"pp_y"]<-extent(pour_points[[i]])[3]
  
}

```



# Nutrients per basin

```{r}
basins_nutri<-read.csv(here("output_data/Nutrients/N_P_unconnected_per_basin.csv")) %>% 
  dplyr::select(-X)
```

# Distribute

We distributed the sediment export across all points weighted by the mean annual discharge of each river

```{r}
basins_nutri_all<-left_join(data_per_river, basins_nutri, by = c("MAIN_BAS")) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry, MAIN_BAS, riv_dis) 

basins_nutri_dist<-basins_nutri_all %>% 
  group_by(MAIN_BAS) %>% 
  summarise(Total_discharge = sum(riv_dis)) %>% 
  left_join(., basins_nutri_all, by = "MAIN_BAS") %>% 
  mutate(prop_dis = riv_dis/Total_discharge,
         N_pourpoint = prop_dis * N,
         P_pourpoint = prop_dis * P)

write_csv(basins_nutri_dist, here("output_data/Nutrients/Fiji_unconnected_nutrients_at_pourpoints.csv"))
  
```

# Nutrient export at each pourpoint

```{r}
pour_points<-basins_nutri_dist
coordinates(pour_points) <- ~pp_x+pp_y
pour_points<-st_as_sf(pour_points)
pour_points<-pour_points %>% 
  dplyr::select(HYRIV_ID, MAIN_BAS, N, P, N_pourpoint, P_pourpoint)

st_crs(pour_points)<-"+proj=tmerc +lat_0=-17 +lon_0=178.75 +k=0.9998548 +x_0=2000000 +y_0=4000000 +ellps=WGS72 +units=m +no_defs "

st_write(pour_points, here("output_data/Rivers/Fiji_unconnected_pourpoints.shp"), delete_layer = T)
```



# Combine with spatil info
```{r}
#pour_points<-left_join(basins_pts, basins_nutri_dist, by = c("HYRIV_ID", "HYBAS_ID","X", "Y", "riv_dis_m3_pyr")) %>% 
#  dplyr::select("X", "Y") %>% 
#  st_intersection(pnts,.)
```

# Diffusion model

Plume function

```{r}
sed_flow_N<-function(pp_sf,#list of pour points
                   ocean_raster,
                   buffer_value,#buffer from pour point
                   resolution_raster,#in meters
                   searchdistance #max searching distance to snap the points to the coast
                   
){
  #set initial sediment value
  initial.value<-pp_sf@data$N_pourpoint
  #create buffer around point and clip ocean raster
  point<-st_as_sf(pp_sf,coords=c("longitude.y","latitude.y"))#first need to convert to sf object
  point_buff<-st_buffer(point, buffer_value)#
  r1<-crop(ocean_raster,extent(point_buff),snap = "near")
  
  #create raster to match point location to ocean raster
  #for a new version we can use the function nearest.raster.point, but I had already solved this issue 
  #rasterizing the point
  
  point_1000<-st_buffer(point, 500)#
  #create raster of pour point
  r2  <- raster(ncol=1, nrow=1, xmn=extent(point_1000)[1], xmx=extent(point_1000)[2], ymn=extent(point_1000)[3], ymx=extent(point_1000)[4])
  crs(r2)<-crs(ocean_raster)
  r2[]<-initial.value
  
  #now sum to match rasters of different extent
  
  extend_all =
    function(rasters){
      extent(Reduce(extend,rasters))
    }
  
  sum_all =
    function(rasters, extent){
      re = lapply(rasters, function(r){extend(r,extent)})
      Reduce("+", re)
    }
  
  rasterOptions(tolerance = 1)
  r3 = sum_all(list(r1,r2), extend_all(list(r1,r2)))
  
  #identify if points are on the coast
  
  if(length(which(r3[]>0))< 1){
    snap_point<-nearestLand(coordinates(r2)[],r1,searchdistance)
    pp_sf@coords<-snap_point
    point<-st_as_sf(pp_sf,coords=c("longitude.y","latitude.y"))
    point_1000<-st_buffer(point, 500)#
    #create raster of pour point
    r2  <- raster(ncol=1, nrow=1, xmn=extent(point_1000)[1], xmx=extent(point_1000)[2], ymn=extent(point_1000)[3], ymx=extent(point_1000)[4])
    crs(r2)<-crs(ocean_raster)
    r2[]<-initial.value
    r3 = sum_all(list(r1,r2), extend_all(list(r1,r2)))
  }
  
  #find exact pour point position
  pour_point <- which(r3[] >0)
  
  fromCoords<-pp_sf@coords
  
  raster_temp<-r3
  r<-raster_temp
  
  #create transition layer to be used in cost layer
  transition_layer<-transition(r1,transitionFunction=mean, directions=8)
  
  transition_layer<-geoCorrection(transition_layer,scl=FALSE)
  
  cost_layer<-accCost(transition_layer, fromCoords)
  #calculate distance frequencies
  
  
  initial.value<-pp_sf@data$N_pourpoint
  
  values<-rasterToPoints(cost_layer)[,3]
  frequency_distances<-as.data.frame(table(round(values,1)))
  frequency_distances<-subset(frequency_distances,frequency_distances[1] != Inf)
  frequency_distances[,1]<-as.character(frequency_distances[,1])
  frequency_distances[,1]<-as.numeric(frequency_distances[,1])
  new.values<-initial.value
  raster_temp[pour_point]<-initial.value*0.005  ##Decay parameter
  
  for(i in 2:nrow(frequency_distances))
  {
    cellstoreplace<-which(round(cost_layer[],1)==frequency_distances[i,1])
    percell = initial.value * 0.005  ## decay parameter
    sumcells = percell * length(cellstoreplace)
    remain = initial.value - sumcells
    initial.value = remain
    raster_temp[cellstoreplace]<-percell
    if(remain < pp_sf@data$N*0.0005) {
      break
    }
  }
  raster_temp[which(raster_temp[]==0)]<-NA
  if(length(unique(raster_temp[]))>1){
    raster_temp<-trim(raster_temp)
  }
  return(raster_temp)
}
```

```{r}
sed_flow_P<-function(pp_sf,#list of pour points
                   ocean_raster,
                   buffer_value,#buffer from pour point
                   resolution_raster,#in meters
                   searchdistance #max searching distance to snap the points to the coast
                   
){
  #set initial sediment value
  initial.value<-pp_sf@data$P_pourpoint
  #create buffer around point and clip ocean raster
  point<-st_as_sf(pp_sf,coords=c("longitude.y","latitude.y"))#first need to convert to sf object
  point_buff<-st_buffer(point, buffer_value)#
  r1<-crop(ocean_raster,extent(point_buff),snap = "near")
  
  #create raster to match point location to ocean raster
  #for a new version we can use the function nearest.raster.point, but I had already solved this issue 
  #rasterizing the point
  
  point_1000<-st_buffer(point, 500)#
  #create raster of pour point
  r2  <- raster(ncol=1, nrow=1, xmn=extent(point_1000)[1], xmx=extent(point_1000)[2], ymn=extent(point_1000)[3], ymx=extent(point_1000)[4])
  crs(r2)<-crs(ocean_raster)
  r2[]<-initial.value
  
  #now sum to match rasters of different extent
  
  extend_all =
    function(rasters){
      extent(Reduce(extend,rasters))
    }
  
  sum_all =
    function(rasters, extent){
      re = lapply(rasters, function(r){extend(r,extent)})
      Reduce("+", re)
    }
  
  rasterOptions(tolerance = 1)
  r3 = sum_all(list(r1,r2), extend_all(list(r1,r2)))
  
  #identify if points are on the coast
  
  if(length(which(r3[]>0))< 1){
    snap_point<-nearestLand(coordinates(r2)[],r1,searchdistance)
    pp_sf@coords<-snap_point
    point<-st_as_sf(pp_sf,coords=c("longitude.y","latitude.y"))
    point_1000<-st_buffer(point, 500)#
    #create raster of pour point
    r2  <- raster(ncol=1, nrow=1, xmn=extent(point_1000)[1], xmx=extent(point_1000)[2], ymn=extent(point_1000)[3], ymx=extent(point_1000)[4])
    crs(r2)<-crs(ocean_raster)
    r2[]<-initial.value
    r3 = sum_all(list(r1,r2), extend_all(list(r1,r2)))
  }
  
  #find exact pour point position
  pour_point <- which(r3[] >0)
  
  fromCoords<-pp_sf@coords
  
  raster_temp<-r3
  r<-raster_temp
  
  #create transition layer to be used in cost layer
  transition_layer<-transition(r1,transitionFunction=mean, directions=8)
  
  transition_layer<-geoCorrection(transition_layer,scl=FALSE)
  
  cost_layer<-accCost(transition_layer, fromCoords)
  #calculate distance frequencies
  
  
  initial.value<-pp_sf@data$P_pourpoint
  
  values<-rasterToPoints(cost_layer)[,3]
  frequency_distances<-as.data.frame(table(round(values,1)))
  frequency_distances<-subset(frequency_distances,frequency_distances[1] != Inf)
  frequency_distances[,1]<-as.character(frequency_distances[,1])
  frequency_distances[,1]<-as.numeric(frequency_distances[,1])
  new.values<-initial.value
  raster_temp[pour_point]<-initial.value*0.005  ##Decay parameter
  
  for(i in 2:nrow(frequency_distances))
  {
    cellstoreplace<-which(round(cost_layer[],1)==frequency_distances[i,1])
    percell = initial.value * 0.005  ## decay parameter
    sumcells = percell * length(cellstoreplace)
    remain = initial.value - sumcells
    initial.value = remain
    raster_temp[cellstoreplace]<-percell
    if(remain < pp_sf@data$N*0.0005) {
      break
    }
  }
  raster_temp[which(raster_temp[]==0)]<-NA
  if(length(unique(raster_temp[]))>1){
    raster_temp<-trim(raster_temp)
  }
  return(raster_temp)
}
```

Avoid reprojecting ocean if possible - takes awhile

```{r}
#ocean_raster<-raster(here("raw_data/Global/oceans_moll.tif"))

#ocean_raster<-projectRaster(ocean_raster, crs = as.character(crs(stp_pp_proj)))

#writeRaster(ocean_raster, here("projected_data/oceans_moll_proj.tif"))

ocean_raster<-raster(here("projected_data/oceans_moll_proj.tif"))
```


```{r}
p_extent=st_as_sfc(st_bbox(pour_points))
p_extent_sub = st_make_grid(p_extent,n = c(40,20)) %>%
               st_as_sf() %>% 
               rename(geom=x) %>%
               mutate(group=1:nrow(.))
tmap::tm_shape(p_extent_sub)+tmap::tm_polygons()
pour_points = st_join(pour_points, p_extent_sub, join = st_intersects) %>% 
              mutate(ID=1:nrow(.)) %>% 
  as_Spatial

  point_list<-split(pour_points,as.character(pour_points@data$ID))
  re = mclapply(point_list, sed_flow_N, ocean_raster, 80000, c(1110,894), 90000, mc.cores = 1)
  #Check to see if we should change buffer value
  
  # Set extent for all outputs to the max extent needed, e.g., newextent
  newextent<-extent(Reduce(extend,re)) # Get max extent of all objects
  re_ext=mclapply(re, extend, newextent, mc.cores=1) # Use fewer cores as this gets more memory heavy
  gc()
  
  # Reclass NAs to 0
  re_ext = mclapply(re_ext, mc.cores = 1, function(x) reclassify(x, cbind(NA,0))) # Reclass NA to 0, in a more memory friendly way,apparently...
  gc()

  # Add all rasters in the group together + mask out land areas is desired
  sed_plume_merge = Reduce("+", re_ext) 
  sed_plume_merge = sed_plume_merge * ocean_raster # mask out land; disregard the warning
  
  writeRaster(sed_plume_merge, here(paste0("output_data/Nutrients/Fiji_unconnected_N_plumes.tif")))

```

```{r}
pour_points<-basins_nutri_dist
coordinates(pour_points) <- ~pp_x+pp_y
pour_points<-st_as_sf(pour_points)
pour_points<-pour_points %>% 
  dplyr::select(HYRIV_ID, MAIN_BAS, N, P, N_pourpoint, P_pourpoint)
st_crs(pour_points)<-"+proj=tmerc +lat_0=-17 +lon_0=178.75 +k=0.9998548 +x_0=2000000 +y_0=4000000 +ellps=WGS72 +units=m +no_defs "

p_extent=st_as_sfc(st_bbox(pour_points))
p_extent_sub = st_make_grid(p_extent,n = c(40,20)) %>%
               st_as_sf() %>% 
               rename(geom=x) %>%
               mutate(group=1:nrow(.))
tmap::tm_shape(p_extent_sub)+tmap::tm_polygons()
pour_points = st_join(pour_points, p_extent_sub, join = st_intersects) %>% 
              mutate(ID=1:nrow(.)) %>% 
  as_Spatial

  point_list<-split(pour_points,as.character(pour_points@data$ID))
  re = mclapply(point_list, sed_flow_P, ocean_raster, 80000, c(1110,894), 90000, mc.cores = 1)
  
  # Set extent for all outputs to the max extent needed, e.g., newextent
  newextent<-extent(Reduce(extend,re)) # Get max extent of all objects
  re_ext=mclapply(re, extend, newextent, mc.cores=1) # Use fewer cores as this gets more memory heavy
  gc()
  
  # Reclass NAs to 0
  re_ext = mclapply(re_ext, mc.cores = 1, function(x) reclassify(x, cbind(NA,0))) # Reclass NA to 0, in a more memory friendly way,apparently...
  gc()

  # Add all rasters in the group together + mask out land areas is desired
  sed_plume_merge = Reduce("+", re_ext) 
  sed_plume_merge = sed_plume_merge * ocean_raster # mask out land; disregard the warning
  
  writeRaster(sed_plume_merge, here(paste0("output_data/Nutrients/Fiji_unconnected_P_plumes.tif")))

```
