---
title: "Untitled"
author: "Caitie"
date: "16/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
#library(startR)
library(here)
library(gdalUtils)
library(tabularaster)
library(units)
library(rgdal)
library(lwgeom)
library(pbmcapply)
library(fasterize)
#devtools::install_github("rspatial/raster")
library(raster)

t_crs<-"+proj=aea +lat_1=-9 +lat_2=-26 +lat_0=-17 +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```

# Basins

```{r}
fiji_basins12<-st_read(here("projected_data/Basins/Fiji_basins12.shp")) %>% 
  group_by(MAIN_BAS) %>% 
  summarise(area_km2 = sum(area_km2, na.rm = T))

fiji_basins12<-fiji_basins12 %>% 
  mutate(ID = seq(from = 1, to =nrow(fiji_basins12), 1)) %>% 
  st_transform(., crs = t_crs)
```

# Rivers

```{r}
rivers<-st_read(here("raw_data/Rivers/RiverATLAS_v10_shp/RiverATLAS_v10_australia.shp"))

rivers_proj<-st_transform(rivers, t_crs)

e<-extent(fiji_basins12)

crop_rivers<-st_crop(rivers_proj, e) %>% 
  dplyr::select(HYRIV_ID, MAIN_RIV, NEXT_DOWN, dis_m3_pyr)
```
# N and P pollution

```{r}
N_cell_septic<-raster(here("output_data/Nutrients/Septic_N.tif"))

P_cell_septic<-raster(here("output_data/Nutrients/Septic_P.tif"))

N_cell_direct<-raster(here("output_data/Nutrients/Direct_N.tif"))

P_cell_direct<-raster(here("output_data/Nutrients/Direct_P.tif"))

```


# Create buffers

```{r}
buff<-seq(from = 10, to = 50, by = 10) %>% as.list()

create_buff<-function(x){
  
buffer_rivers<-st_buffer(crop_rivers, dist = x) %>% 
  mutate(ID = 1) %>% 
  st_cast(., "POLYGON")

buffer_ras<-fasterize(buffer_rivers, N_cell_septic)

writeRaster(buffer_ras, paste0("/home/kuempel/Fiji_sewage/output_data/Rivers/buffers/buffer_rivers_",x,".tif"),overwrite = T)

}

pbmclapply(buff, create_buff, mc.cores = 5, mc.style = "ETA")
```
```{r}
buff<-seq(from = 100, to = 500, by = 100) %>% as.list()

create_buff<-function(x){
  
buffer_rivers<-st_buffer(crop_rivers, dist = x) %>% 
  mutate(ID = 1) %>% 
  st_cast(., "POLYGON")

buffer_ras<-fasterize(buffer_rivers, N_cell_septic)

writeRaster(buffer_ras, paste0("/home/kuempel/Fiji_sewage/output_data/Rivers/buffers/buffer_rivers_",x,".tif"),overwrite = T)

}

pbmclapply(buff, create_buff, mc.cores = 5, mc.style = "ETA")
```

# Clear memory
```{r}
gc()
```

# Change buffer area to N/P values

```{r}
buffer_list<-list.files(path = here("output_data//Rivers/buffers"), pattern = "buffer_rivers_", full.names = T)

buffer_list2<-buffer_list[grep(buffer_list, pattern = ".tif$")]


buffer_N_P<-function(x){
  
  buffer_ras<-raster(x)
  num<-as.numeric(regmatches(x, gregexpr("[[:digit:]]+", x)))
  
  N<-N_ras * buffer_ras
  P<-P_ras * buffer_ras
  
  basin_N<-raster::extract(N, fiji_basins12, fun=sum, na.rm=TRUE, df=TRUE)
  basin_P<-raster::extract(P, fiji_basins12, fun=sum, na.rm=TRUE, df=TRUE)
  

  basins_nutri_df<-full_join(basin_N, fiji_basins12, by = "ID") %>% 
    rename(N = layer) %>% 
    full_join(., basin_P, by = "ID") %>% 
    rename(P = layer) %>% 
    dplyr::select(ID, N, P, MAIN_BAS)
  
  
  write.csv(basins_nutri_df, paste0("/home/kuempel/Fiji_sewage/output_data/Nutrients/buffers/N_P_", name,"_per_basin_",num,"_buff.csv"))

  }

```


```{r}
N_ras<-N_cell_septic
P_ras<-P_cell_septic
name<-"septic"

pbmclapply(buffer_list2, buffer_N_P, mc.cores = 5, mc.style = "ETA")
```

```{r}
N_ras<-N_cell_direct
P_ras<-P_cell_direct
name<-"direct"

pbmclapply(buffer_list2, buffer_N_P, mc.cores = 5, mc.style = "ETA")
```


# Calculate N and P for different buffer distances and leaching rates

```{r}
N_P_buffers<-list.files(here("output_data/Nutrients/buffers"), pattern = "septic", full.names = T)

N_P_buffers2<-N_P_buffers[grep(N_P_buffers, pattern = "Coast")]

N_P_buffers3<-N_P_buffers[!N_P_buffers %in% N_P_buffers2]

leach<-seq(0.1,1,by = 0.1)
df2<-c()

for(i in 1:length(N_P_buffers3)){
  name<-N_P_buffers3[i]
  buff<-parse_number(name)
  print(buff)
  c<-read.csv(N_P_buffers3[i])
  n<-sum(c$N, na.rm = T)
  p<-sum(c$P, na.rm = T)
  
  for(k in 1:length(leach)){
    rm(df)
    print(leach[k])
    n_leach<-n*leach[k]
    p_leach<-p*leach[k]
    
    df<-data.frame(buffer = buff, leach_rate = leach[k], N = n_leach, P = p_leach)
    
    df2<-rbind(df2, df)
  }
  
  
}

df2<-df2 %>% 
  mutate(type = "septic")

```


```{r}
N_P_buffers_direct<-list.files(here("output_data/Nutrients/buffers"), pattern = "direct", full.names = T)

N_P_buffers_direct2<-N_P_buffers_direct[grep(N_P_buffers_direct, pattern = "Coast")]

N_P_buffers_direct3<-N_P_buffers_direct[!N_P_buffers_direct %in% N_P_buffers_direct2]

df4<-c()

for(i in 1:length(N_P_buffers_direct3)){
  name<-N_P_buffers_direct3[i]
  buff<-parse_number(name)
  c<-read.csv(N_P_buffers_direct3[i])
  n<-sum(c$N, na.rm = T)
  p<-sum(c$P, na.rm = T)
  
  for(k in 1:length(leach)){
    rm(df)
    print(leach[k])
    n_leach<-n*leach[k]
    p_leach<-p*leach[k]
    
    df<-data.frame(buffer = buff, leach_rate = leach[k], N = n_leach, P = p_leach)
    
    df4<-rbind(df4, df)
  }
  
}

df4<- df4 %>% 
  mutate(type = "direct")
```


```{r}
done<-rbind(df2, df4)

write.csv(done, here("output_data/Sensitivity/Leaching_buffer_sensitivity.csv"))
```

